### ISSUE TITLE
Pushover problem

### ISSUE THREAD

**Issue by strauhmanis** [thp/urlwatch#102]
Hello!

I'm running urlwatch on macOS 10.12 (with Python 3.5.2 via Homebrew).

urlwatch is installed with the following commands:
```
python3 -m pip install pyyaml minidb requests keyring --user
python3 -m pip install chump --user
```

Default urlwatch.yaml is edited according to my Pushover settings:
```
  pushover:
    app: 'urlwatch'
    enabled: true
    user: 'xxxxxxxxxxxxxxxxxxxx'
```

Now, when running urlwatch I get the following message:
```
urlwatch 2.5, Copyright 2008-2016 Thomas Perl
Website: http://thp.io/2008/urlwatch/
watched 1 URLs in 0 seconds
Failed to load or connect to pushover - are the dependencies installed and configured?
Traceback (most recent call last):
  File "/Users/ervsts/Downloads/urlwatch-master/lib/urlwatch/reporters.py", line 390, in submit
    service = self.web_service_get()
  File "/Users/ervsts/Downloads/urlwatch-master/lib/urlwatch/reporters.py", line 405, in web_service_get
    app = chump.Application(self.config['app'])
  File "/Users/ervsts/Library/Python/3.5/lib/python/site-packages/chump/__init__.py", line 198, in __init__
    self.token = unicode(token) #: A :py:obj:`string` of the application's API token.
  File "/Users/ervsts/Library/Python/3.5/lib/python/site-packages/chump/__init__.py", line 209, in __setattr__
    raise ValueError('Bad application token: expected string matching [a-zA-Z0-9]{30}, got {!r}'.format(value))
IndexError: tuple index out of range
```

Asking for assistance, please!

**Comment by thp** [comment]
This is a bug in the chump library, I've forwarded the bug report here:

https://github.com/karanlyons/chump/issues/8
