### ISSUE TITLE
AttributeError 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by jamesarm97** [thp/urlwatch#108]
I am just installing this (installed all dependancies) and get this error when I run it for the first time. Any thought on what I should look at?:

Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 4, in <module>
    **import**('pkg_resources').run_script('urlwatch==2.5', 'urlwatch')
  File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 1659, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.4/site-packages/urlwatch-2.5-py3.4.egg/EGG-INFO/scripts/urlwatch", line 92, in <module>
  File "/usr/lib/python3.4/site-packages/urlwatch-2.5-py3.4.egg/urlwatch/storage.py", line 156, in **init**
  File "/usr/lib/python3.4/site-packages/urlwatch-2.5-py3.4.egg/urlwatch/storage.py", line 294, in load
  File "/usr/lib/python3.4/site-packages/urlwatch-2.5-py3.4.egg/urlwatch/storage.py", line 115, in merge
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by paci4416** [comment]
Same here , seems like it's trying to load the config file 'urlwatch.yaml' in load function, but since it's doesn't exist it returns None.
