### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2018' in position 67: ordinal not in range(128)

### ISSUE THREAD

**Issue by shaun-ba** [thp/urlwatch#152]
```
Traceback (most recent call last):
  File "/usr/local/bin/urlwatch", line 101, in <module>
    urlwatch_command.run()
  File "/usr/local/lib/python3.4/dist-packages/urlwatch/command.py", line 167, in run
    self.urlwatcher.close()
  File "/usr/local/lib/python3.4/dist-packages/urlwatch/main.py", line 96, in close
    self.report.finish()
  File "/usr/local/lib/python3.4/dist-packages/urlwatch/handler.py", line 125, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/usr/local/lib/python3.4/dist-packages/urlwatch/reporters.py", line 92, in submit_all
    subclass(report, cfg, job_states, duration).submit()
  File "/usr/local/lib/python3.4/dist-packages/urlwatch/reporters.py", line 313, in submit
    print(self._green(line))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2018' in position 67: ordinal not in range(128)
```

**Comment by thp** [comment]
Make sure you have a POSIX locale set that uses UTF-8, see also: #51
