### ISSUE TITLE
Allow specifying : (colon) and , (comma) in grep filters

### ISSUE THREAD

**Issue by monoverse** [thp/urlwatch#154]
I would like to grep a web page for price changes and tried to set up a filter like this:
`filter: html2text,grep:€11,59,strip`

This results in the following error because the subfilter "€11,59" is split at the comma:
`Traceback (most recent call last):               
  File "/home/xxxxx/.virtualenvs/urlwatch/lib/python3.6/site-packages/urlwatch/handler.py", line 79, in process                                                                                          
    data = FilterBase.process(filter_kind, subfilter, self, data)                                  
  File "/home/xxxxx/.virtualenvs/urlwatch/lib/python3.6/site-packages/urlwatch/filters.py", line 83, in process                                                                                          
    raise ValueError('Unknown filter kind: %s:%s' % (filter_kind, subfilter))                      
ValueError: Unknown filter kind: 59:None`

As a workaround i can use:
`filter: html2text,grep:€11.?59,strip`

This kinda works for me because now it matches any single character at this point. But what if I want to specifically match the comma? Is this possible at all?

many thanks!

**Comment by jwilk** [comment]
Comma can be escaped as `\054`.
