### ISSUE TITLE
Is this error harmless?

### ISSUE THREAD

**Issue by gaia** [thp/urlwatch#163]
```
--- @	Sat, 26 Aug 2017 18:45:03 +0000
+++ @	Sat, 26 Aug 2017 18:45:22 +0000
@@ -153,7 +153,7 @@
 
 <div class="profile container" style="margin-top: 5px">
Traceback (most recent call last):
  File "/usr/local/bin/urlwatch", line 101, in <module>
    urlwatch_command.run()
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/command.py", line 167, in run
    self.urlwatcher.close()
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/main.py", line 96, in close
    self.report.finish()
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/handler.py", line 125, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/reporters.py", line 92, in submit_all
    subclass(report, cfg, job_states, duration).submit()
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/reporters.py", line 315, in submit
    print(self._red(line))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 218: ordinal not in range(128)
 ```

**Comment by thp** [comment]
Make sure you are using a UTF-8 locale, as per #51.
