### ISSUE TITLE
Error when printing Unicode text

### ISSUE THREAD

**Issue by MrLafarge** [thp/urlwatch#168]
Dear Thomas,

I really enjoy using urlwatch its really powerful. Today I encountered the (usual) problem with Unicode texts in Python:
```
Traceback (most recent call last):
  File "./urlwatch", line 101, in <module>
    urlwatch_command.run()
  File "/home/martin/urlwatch/lib/urlwatch/command.py", line 167, in run
    self.urlwatcher.close()
  File "/home/martin/urlwatch/lib/urlwatch/main.py", line 96, in close
    self.report.finish()
  File "/home/martin/urlwatch/lib/urlwatch/handler.py", line 128, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/home/martin/urlwatch/lib/urlwatch/reporters.py", line 92, in submit_all
    subclass(report, cfg, job_states, duration).submit()
  File "/home/martin/urlwatch/lib/urlwatch/reporters.py", line 315, in submit
    print(self._red(line))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6927-6935: ordinal not in range(128) 
```
What would be a good way to solve this problem?

Many thanks,
Martin

**Comment by MrLafarge** [comment]
Found a solution in the forum: env LC_ALL=en_US.UTF-8 urlwatch
