### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by agomper** [thp/urlwatch#185]
I am trying to run urlwatch on a Raspberry Pi but I am always getting this error after calling the program:

> Traceback (most recent call last):
>   File "/usr/local/bin/urlwatch", line 101, in <module>
>     urlwatch_command.run()
>   File "/usr/local/lib/python3.4/dist-packages/urlwatch/command.py", line 167, in run
>     self.urlwatcher.close()
>   File "/usr/local/lib/python3.4/dist-packages/urlwatch/main.py", line 96, in close
>     self.report.finish()
>   File "/usr/local/lib/python3.4/dist-packages/urlwatch/handler.py", line 125, in finish
>     ReporterBase.submit_all(self, self.job_states, duration)
>   File "/usr/local/lib/python3.4/dist-packages/urlwatch/reporters.py", line 92, in submit_all
>     subclass(report, cfg, job_states, duration).submit()
>   File "/usr/local/lib/python3.4/dist-packages/urlwatch/reporters.py", line 362, in submit
>     mailer.send(msg)
>   File "/usr/local/lib/python3.4/dist-packages/urlwatch/mailer.py", line 82, in send
>     s = smtplib.SMTP(self.smtp_server, self.smtp_port)
>   File "/usr/lib/python3.4/smtplib.py", line 242, in __init__
>     (code, msg) = self.connect(host, port)
>   File "/usr/lib/python3.4/smtplib.py", line 321, in connect
>     self.sock = self._get_socket(host, port, self.timeout)
>   File "/usr/lib/python3.4/smtplib.py", line 292, in _get_socket
>     self.source_address)
>   File "/usr/lib/python3.4/socket.py", line 509, in create_connection
>     raise err
>   File "/usr/lib/python3.4/socket.py", line 500, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused

I don´t really know what to do now.

**Comment by agomper** [comment]
Ok, I have just found out it is related with the email configuration. Is there any kind of example I can follow? Thank you.

**Comment by agomper** [comment]
Sorry for being impulsive, I got the solution.

[https://github.com/thp/urlwatch/issues/82](url)
