### ISSUE TITLE
Problem getting pushover to work

### ISSUE THREAD

**Issue by engowen** [thp/urlwatch#198]
I'm tracking the clock and I do get the changes on the console. I tried to get pushover to work and  got the dependency chump installed. There are only 2 parameters in urlwatch.yaml to set, app being the api token key and the user key. I'd supplied both.

  pushover:
    app: 'a5dzb[myAPITokenKey]...'
    enabled: true
    user: 'uwpe8uw[myUserKey]...' 

when I ran urlwatch, this is the complete output. Any idea what's the problem? I'm using the latest version of urlwatch on my Mac.

===========================================================================
01. CHANGED: time
===========================================================================

---------------------------------------------------------------------------
CHANGED: time (https://time.is/)
---------------------------------------------------------------------------
--- @	Sun, 28 Jan 2018 10:13:07 +0000
+++ @	Sun, 28 Jan 2018 10:17:20 +0000
@@ -1 +1 @@
-10:13:07
+10:17:20

---------------------------------------------------------------------------

-- 
urlwatch 2.7, Copyright 2008-2016 Thomas Perl
Website: http://thp.io/2008/urlwatch/
watched 1 URLs in 0 seconds
Failed to load or connect to pushover - are the dependencies installed and configured?
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urlwatch/reporters.py", line 389, in submit
    service = self.web_service_get()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urlwatch/reporters.py", line 404, in web_service_get
    app = chump.Application(self.config['app'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chump/__init__.py", line 208, in __init__
    self.token = unicode(token) #: A :py:obj:`string` of the application's API token.
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chump/__init__.py", line 222, in __setattr__
    self._authenticate()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chump/__init__.py", line 255, in _authenticate
    self._request('validate')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/chump/__init__.py", line 319, in _request
    response = urlopen(url, bytes(urlencode(data), 'utf-8', 'strict') if data else None)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)>

Thanks,
Brian

**Comment by engowen** [comment]
Sorry, apparently it is the MAC and Python 3.6 that caused the problem. Following the guide [here](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error) fixed the issue, by running Applications/Python\ 3.6/Install\ Certificates.command
