### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2013' in position 59: character maps to <undefined>

### ISSUE THREAD

**Issue by yleyvag** [thp/urlwatch#210]
Traceback (most recent call last):
  File "urlwatch", line 106, in <module>
    urlwatch_command.run()
  File "C:\Users\xxxxx\Downloads\urlwatch\lib\urlwatch\command.py", line 167, in run
    self.urlwatcher.close()
  File "C:\Users\xxxxx\Downloads\urlwatch\lib\urlwatch\main.py", line 96, in close
    self.report.finish()
  File "C:\Users\xxxxx\Downloads\urlwatch\lib\urlwatch\handler.py", line 128, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "C:\Users\xxxxx\Downloads\urlwatch\lib\urlwatch\reporters.py", line 92, in submit_all
    subclass(report, cfg, job_states, duration).submit()
  File "C:\Users\xxxxx\Downloads\urlwatch\lib\urlwatch\reporters.py", line 315, in submit
    print(self._red(line))
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python35\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]

**Comment by thp** [comment]
It seems like you system encoding is set to https://en.wikipedia.org/wiki/Code_page_850.

Can you try using an UTF-8 locale?

**Comment by yleyvag** [comment]
How can I do that? I'm using Windows 10 x64.

**Comment by thp** [comment]
According to https://www.python.org/dev/peps/pep-0528/, it might be as easy as upgrading to Python 3.6.

**Comment by thp** [comment]
This might also be useful: https://stackoverflow.com/a/9642011/1047040

<q>Use the command `chcp 65001` before starting Python.</q>

**Comment by yleyvag** [comment]
the problem solved installing Python 3.6.4
