### ISSUE TITLE
Errors Raspbian Stretch

### ISSUE THREAD

**Issue by bones78** [thp/urlwatch#236]
Hi all, 
I have installed urlwatch on a Raspberry Pi3b+ (Raspbian Stretch). 
I have used the following commands:
`sudo apt-get install python3-pip` 
`sudo pip3 install urlwatch` 
`python3 -m pip install pyyaml minidb requests keyring appdirs chump` 

If I start urlwatch or edit the files I get the following error messages:
`Error initializing plugin EntryPoint('Gnome', 'keyrings.alt.Gnome', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/keyring/backend.py", line 148, in _load_plugins
    init_func = ep.load()
  File "/home/pi/.local/lib/python3.5/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Gnome.py", line 11, in <module>
    from keyring.py27compat import unicode_str
ImportError: cannot import name 'unicode_str'
Error initializing plugin EntryPoint('kwallet', 'keyrings.alt.kwallet', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/keyring/backend.py", line 148, in _load_plugins
    init_func = ep.load()
  File "/home/pi/.local/lib/python3.5/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/kwallet.py", line 6, in <module>
    from keyring.py27compat import unicode_str
ImportError: cannot import name 'unicode_str'`

The program itself runs and it checks the websites correctly. How can I fix the error messages?

**Comment by thp** [comment]
This sounds similar: https://github.com/xybu/onedrived-dev/issues/36

Did you try running the suggested fix of `sudo pip3 install --upgrade keyrings.alt`?

**Comment by bones78** [comment]
Thanks a lot, that solves the problem!
Great program, by the way!

**Comment by gaia** [comment]
This is what I am getting on Raspbian Stretch:

```
sudo pip3 install --upgrade keyrings.alt
Collecting keyrings.alt
  Downloading https://files.pythonhosted.org/packages/f7/db/202fe99c9f6d75c7810cb3af7d791479df0dd942f2bac2425646c0ad3db8/keyrings.alt-3.1-py2.py3-none-any.whl
Collecting six (from keyrings.alt)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, keyrings.alt
  Found existing installation: six 1.10.0
    Not uninstalling six at /usr/lib/python3/dist-packages, outside environment /usr
  Found existing installation: keyrings.alt 1.3
    Not uninstalling keyrings.alt at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed keyrings.alt-3.1 six-1.11.0
pi@pi:~ $ sudo python3 -m pip install pyyaml minidb requests keyring appdirs
Collecting pyyaml
  HTTP error 404 while getting https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)
  Could not install requirement pyyaml from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff because of error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl
Could not install requirement pyyaml from https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff because of HTTP error 404 Client Error: Not Found for url: https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl for URL https://www.piwheels.org/simple/pyyaml/PyYAML-4.1-cp35-cp35m-linux_armv7l.whl#sha256=a5b125a24244830d574ccfd8fab861198d2ffe491b73179ffd75abf78caee6ff (from https://www.piwheels.org/simple/pyyaml/)
```
