### ISSUE TITLE
Error on initializing 

### ISSUE THREAD

**Issue by Sn0wCooder** [thp/urlwatch#244]
```
pi@raspberrypi:~ $ urlwatch 
Traceback (most recent call last):
  File "/usr/local/bin/urlwatch", line 4, in <module>
    __import__('pkg_resources').run_script('urlwatch==2.11', 'urlwatch')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1500, in run_script
    script_code = compile(script_text, script_filename, 'exec')
  File "/usr/local/lib/python2.7/dist-packages/urlwatch-2.11-py2.7.egg/EGG-INFO/scripts/urlwatch", line 67
    ...
    ^
SyntaxError: invalid syntax
```

**Comment by thp** [comment]
You have to use Python 3, not Python 3 for urlwatch.
