### ISSUE TITLE
gmail Smtp via cron

### ISSUE THREAD

**Issue by do-d1** [thp/urlwatch#260]
hello
from ubuntu cli everything runs great.
im trying to setup to run from cron but it looks like its failing to retrieve password

`watched 1 URLs in 0 seconds
Traceback (most recent call last):
  File "/usr/local/bin/urlwatch", line 4, in <module>
    __import__('pkg_resources').run_script('urlwatch==2.13', 'urlwatch')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/EGG-INFO/scripts/urlwatch", line 111, in <module>
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/urlwatch/command.py", line 227, in run
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/urlwatch/main.py", line 96, in close
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/urlwatch/handler.py", line 143, in finish
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/urlwatch/reporters.py", line 101, in submit_all
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/urlwatch/reporters.py", line 389, in submit
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/urlwatch/mailer.py", line 92, in send
ValueError: No password available in keyring for smtp.gmail.com, someuser@gmail.com`  

also i tried to not use the keyring by changing urlwatch --edit-config
`    smtp:
      host: 'smtp.gmail.com'
      user: 'someuser@gmail.com'
      password: 'password'
      keyring: false
      port: 587
      starttls: true
`
`watched 1 URLs in 0 seconds
Traceback (most recent call last):
  File "/usr/local/bin/urlwatch", line 4, in <module>
    __import__('pkg_resources').run_script('urlwatch==2.13', 'urlwatch')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/EGG-INFO/scripts/urlwatch", line 111, in <module>
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/urlwatch/command.py", line 227, in run
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/urlwatch/main.py", line 96, in close
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/urlwatch/handler.py", line 143, in finish
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/urlwatch/reporters.py", line 101, in submit_all
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/urlwatch/reporters.py", line 389, in submit
  File "/usr/local/lib/python3.6/dist-packages/urlwatch-2.13-py3.6.egg/urlwatch/mailer.py", line 95, in send
  File "/usr/lib/python3.6/smtplib.py", line 867, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.5.1 Authentication Required. Learn more at\n5.5.1  https://support.google.com/mail/?p=WantAuthError f20-v6sm391615wrh.89 - gsmtp', 'someuser@gmail.com')`

please your advise

**Comment by do-d1** [comment]
i change this: 
`keyring: false` to `keyring: 'false'`
and the plain text user and password are working now from cli.
but still not runs from cron, even when keyring: 'false' i get this message:
`ValueError: No password available in keyring for smtp.gmail.com, someuser@gmail.com`

**Comment by thp** [comment]
Setting `keyring: 'false'` (the string `"false"` as opposed to the boolean value `false`) is probably the same as `keyring: true`.

Have you tried the setup as in https://github.com/thp/urlwatch#e-mail-via-gmail-smtp ?

Also note that it might be that the Secret Service feature for Keyring (which is the one that's likely used on Linux) might not be available when running from cron.

See this: https://pypi.org/project/keyring/#third-party-backends

Maybe try this: https://pypi.org/project/keyrings.cryptfile/

**Comment by janimo** [comment]
Setting env vars in crontab may help https://mail.gnome.org/archives/gnome-keyring-list/2012-December/msg00000.html

**Comment by thp** [comment]
This is now documented here:
https://urlwatch.readthedocs.io/en/latest/reporters.html#e-mail-via-gmail-smtp
