### ISSUE TITLE
Error on Windows 10

### ISSUE THREAD

**Issue by jeffest** [thp/urlwatch#263]
Hello,

I'm having the below error when I try to execute urlwatch on a Windows 10 machine using Python  3.7.0 (x86) (sorry for the formating...) : 
`Migrating cache: C:\Users\jeff.estival\AppData\Local\urlwatch\urlwatch\cache -> C:\Users\jeff.estival\AppData\Local\urlwatch\urlwatch\Cache\cache.db
Traceback (most recent call last):
File "urlwatch", line 107, in <module>                                                                                                                
    urlwatch = Urlwatch(command_config, config_storage, cache_storage, urls_storage)                                                                    
  File "C:\Users\jeff.estival\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urlwatch\main.py", line 66, in __init__                       
    self.urlwatch_config.migrate_cache(self)                                                                                                            
  File "C:\Users\jeff.estival\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urlwatch\migration.py", line 80, in migrate_cache             
    urlwatcher.cache_storage.restore(old_cache_storage.backup())                                                                                        
  File "C:\Users\jeff.estival\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urlwatch\storage.py", line 379, in restore                    
    for guid, data, timestamp, tries in entries:                                                                                                        
  File "C:\Users\jeff.estival\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urlwatch\storage.py", line 375, in backup                     
    data, timestamp, tries = self.load(None, guid)                                                                                                      
ValueError: not enough values to unpack (expected 3, got 2)`

Can you please help ?

**Comment by jeffest** [comment]
On Windows there is a missing dependency : cffi
Then in cffi module, one of the file have an incorrect EOL setting : \Lib\site-packages\win32ctypes\core\cffi\_advapi32.py
After changing the EOL everything works as expected.
