### ISSUE TITLE
html2text print javascript code as Text.

### ISSUE THREAD

**Issue by nille02** [thp/urlwatch#283]
The Content of a <script> Element is converted to normal Text. That's problematic since some <script> Elements are generated for Advertisements and Mark a Website as Changed. 

e.g. 

```
filter: xpath://main[@id='main']//article/div[@class='entry-content'],html2text
kind: url
name: "Jingai Musume 053 \u2013 Cardboard Translations"
url: https://cardboardtranslations.com/jingai-musume-53/

```

**Comment by thp** [comment]
Note that there are multiple html2text conversion methods, you might try a different one, e.g.:

```
filter:
    - xpath://main[@id='main']//article/div[@class='entry-content']
    - html2text:
        method: lynx
kind: url
name: "Jingai Musume 053 \u2013 Cardboard Translations"
url: https://cardboardtranslations.com/jingai-musume-53/
```

Note that this needs the `lynx` package installed. Other methods are listed in `lib/urlwatch/html2txt.py`, e.g. `html2text` (uses the `html2text` command line utility), `bs4` (uses BeautifulSoup 4), `pyhtml2text` (uses the `html2text` Python module).

**Comment by nille02** [comment]
Thank you, i give it a try

**Comment by nille02** [comment]
It gives me an error 

```
---------------------------------------------------------------------------
ERROR: Jingai Musume 053 – Cardboard Translations (https://cardboardtranslations.com/jingai-musume-53/)
---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/niels/.local/lib/python3.5/site-packages/urlwatch/handler.py", line 84, in process
    filter_kind, subfilter = key, item[key]
TypeError: string indices must be integers
---------------------------------------------------------------------------

```

This is the url entry

```
---
filter:
    - xpath://main[@id='main']//article/div[@class='entry-content']
    - html2text:
        method: lynx
kind: url
name: "Jingai Musume 053 \u2013 Cardboard Translations"
url: https://cardboardtranslations.com/jingai-musume-53/
```

Or how do i pass the parameters? 

`filter: xpath://main[@id='main']//article/div[@class='entry-content'],html2text: method: lynx`

didn't work

```
Traceback (most recent call last):
  File "/home/niels/.local/bin/urlwatch", line 107, in <module>
    urlwatch = Urlwatch(command_config, config_storage, cache_storage, urls_storage)
  File "/home/niels/.local/lib/python3.5/site-packages/urlwatch/main.py", line 63, in __init__
    self.load_jobs()
  File "/home/niels/.local/lib/python3.5/site-packages/urlwatch/main.py", line 84, in load_jobs
    jobs = self.urls_storage.load_secure()
  File "/home/niels/.local/lib/python3.5/site-packages/urlwatch/storage.py", line 239, in load_secure
    jobs = self.load()
  File "/home/niels/.local/lib/python3.5/site-packages/urlwatch/storage.py", line 328, in load
    return [JobBase.unserialize(job) for job in yaml.load_all(fp) if job is not None]
  File "/home/niels/.local/lib/python3.5/site-packages/urlwatch/storage.py", line 328, in <listcomp>
    return [JobBase.unserialize(job) for job in yaml.load_all(fp) if job is not None]
  File "/home/niels/.local/lib/python3.5/site-packages/yaml/__init__.py", line 84, in load_all
    yield loader.get_data()
  File "/home/niels/.local/lib/python3.5/site-packages/yaml/constructor.py", line 31, in get_data
    return self.construct_document(self.get_node())
  File "/home/niels/.local/lib/python3.5/site-packages/yaml/composer.py", line 27, in get_node
    return self.compose_document()
  File "/home/niels/.local/lib/python3.5/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/niels/.local/lib/python3.5/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/niels/.local/lib/python3.5/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/niels/.local/lib/python3.5/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/niels/.local/lib/python3.5/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/niels/.local/lib/python3.5/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/niels/.local/lib/python3.5/site-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/home/niels/.local/lib/python3.5/site-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/home/niels/.urlwatch/urls.yaml", line 1, column 80

```

**Comment by nille02** [comment]
The quotes fixed it, tank you very much. 

With this i get a nice text without the <script> content.

**Comment by nille02** [comment]
Is there a way to pass these settings per --add option?

**Comment by kongomongo** [comment]
> Note that there are multiple html2text conversion methods, you might try a different one, e.g.:
> 
> ```
> filter:
>     - xpath://main[@id='main']//article/div[@class='entry-content']
>     - html2text:
>         method: lynx
> kind: url
> name: "Jingai Musume 053 \u2013 Cardboard Translations"
> url: https://cardboardtranslations.com/jingai-musume-53/
> ```
> 
> Note that this needs the `lynx` package installed. Other methods are listed in `lib/urlwatch/html2txt.py`, e.g. `html2text` (uses the `html2text` command line utility), `bs4` (uses BeautifulSoup 4), `pyhtml2text` (uses the `html2text` Python module).

Wouldn't it make sense to add that to the documentation?

https://urlwatch.readthedocs.io/en/latest/filters.html

**Comment by PeterDaveHello** [comment]
Yeah, it'll be great to have it in the document.
