### ISSUE TITLE
Telegram: chat_id, not chat-id

### ISSUE THREAD

**Issue by gumida** [thp/urlwatch#289]
Hello,
I've noticed one little thing while configuring my telegram integration.
In my new installation the field for chat ID was wrong in "urlwatch.edit.yaml":
It should be "chat_id", but was shipped with "chat-id"? (installed via pip)

**Comment by thp** [comment]
Thanks! This is fixed in #276 which isn't yet part of an official release, so that's why you haven't seen this in the code published via pip. Keeping this open until I'll release a new version.

**Comment by thp** [comment]
urlwatch 2.15 released, which includes the fix, you can upgrade with a command like the following:

     pip3 install --user --upgrade urlwatch

Note that depending on how your path is set up, and how you installed the previous version, you might need to use a slightly different command.

**Comment by gumida** [comment]
I've updated to the last version as described. When using"urlwatch --version" now, I'm getting the following output: 

```
root@urlwatch:~# urlwatch --version
Error initializing plugin EntryPoint('Gnome', 'keyrings.alt.Gnome', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/keyring/backend.py", line 163, in _load_plugins
    init_func = ep.load()
  File "/root/.local/lib/python3.5/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Gnome.py", line 11, in <module>
    from keyring.py27compat import unicode_str
ImportError: cannot import name 'unicode_str'
Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/keyring/backend.py", line 163, in _load_plugins
    init_func = ep.load()
  File "/root/.local/lib/python3.5/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 12, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('file', 'keyrings.alt.file', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/keyring/backend.py", line 163, in _load_plugins
    init_func = ep.load()
  File "/root/.local/lib/python3.5/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 12, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('kwallet', 'keyrings.alt.kwallet', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/keyring/backend.py", line 163, in _load_plugins
    init_func = ep.load()
  File "/root/.local/lib/python3.5/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/kwallet.py", line 6, in <module>
    from keyring.py27compat import unicode_str
ImportError: cannot import name 'unicode_str'
Error initializing plugin EntryPoint('pyfs', 'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/keyring/backend.py", line 163, in _load_plugins
    init_func = ep.load()
  File "/root/.local/lib/python3.5/site-packages/entrypoints.py", line 77, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ImportError: No module named 'keyring.util.escape'
urlwatch 2.15
root@urlwatch:~# 
```
Did I do something wrong or is it supposed to be like that? 
```
root@urlwatch:~# pip3 list
appdirs (1.4.3)
asn1crypto (0.24.0)
autopep8 (1.4.1)
beautifulsoup4 (4.6.3)
bs4 (0.0.1)
certifi (2018.10.15)
cffi (1.11.5)
chardet (3.0.4)
colorama (0.4.0)
cryptography (2.3.1)
cssselect (1.0.3)
entrypoints (0.2.3)
fake-useragent (0.1.11)
httplib2 (0.9.2)
idna (2.7)
jeepney (0.4)
keyring (15.1.0)
keyrings.alt (1.3)
lxml (4.2.5)
minidb (2.0.2)
parse (1.9.0)
pip (9.0.1)
py-backwards (0.7)
py-backwards-astunparse (1.5.0.post3)
pyasn1 (0.1.9)
pycodestyle (2.4.0)
pycparser (2.19)
pycrypto (2.6.1)
pycurl (7.43.0)
pyee (5.0.0)
pygobject (3.22.0)
pyppeteer (0.0.25)
pyquery (1.4.0)
python-apt (1.4.0b3)
python-debian (0.1.30)
python-debianbts (2.6.1)
pyxdg (0.25)
PyYAML (3.13)
reportbug (7.1.7)
requests (2.20.0)
requests-html (0.6.6)
SecretStorage (3.1.0)
setuptools (33.1.1)
six (1.11.0)
tqdm (4.28.0)
typed-ast (1.1.0)
urllib3 (1.24)
urlwatch (2.15)
w3lib (1.19.0)
websockets (6.0)
wheel (0.29.0)
root@urlwatch:~# 
```

**Comment by thp** [comment]
Try this next (note that your installed version is 1.3, whereas the newest version is 3.1):

     pip3 install --user --upgrade keyrings.alt

**Comment by gumida** [comment]
@thp This did the trick - thanks for your help :wink:
