### ISSUE TITLE
Error when using --smtp-login

### ISSUE THREAD

**Issue by JsBergbau** [thp/urlwatch#349]
When trying to setup E-Mail Notification via ./urlwatch --smtp-login following is displayed:

`Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/secretstorage/util.py", line 47, in send_and_get_reply
    return self._connection.send_and_get_reply(msg)
  File "/home/pi/.local/lib/python3.5/site-packages/jeepney/integrate/blocking.py", line 49, in send_and_get_reply
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownMethod] ('Keine derartige Schnittstelle »org.freedesktop.DBus.Properties« des Objekts im Pfad /org/freedesktop/secrets/collection/login',)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/secretstorage/collection.py", line 161, in get_default_collection
    return Collection(connection)
  File "/home/pi/.local/lib/python3.5/site-packages/secretstorage/collection.py", line 44, in __init__
    self._collection.get_property('Label')
  File "/home/pi/.local/lib/python3.5/site-packages/secretstorage/util.py", line 65, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/home/pi/.local/lib/python3.5/site-packages/secretstorage/util.py", line 50, in send_and_get_reply
    raise ItemNotFoundException('Item does not exist!') from resp
secretstorage.exceptions.ItemNotFoundException: Item does not exist!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/keyring/backends/SecretService.py", line 52, in get_preferred_collection
    collection = secretstorage.get_default_collection(bus)
  File "/home/pi/.local/lib/python3.5/site-packages/secretstorage/collection.py", line 164, in get_default_collection
    'default', session)
  File "/home/pi/.local/lib/python3.5/site-packages/secretstorage/collection.py", line 145, in create_collection
    raise PromptDismissedException('Prompt dismissed.')
secretstorage.exceptions.PromptDismissedException: Prompt dismissed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./urlwatch", line 111, in <module>
    urlwatch_command.run()
  File "/home/pi/urlwatch/lib/urlwatch/command.py", line 289, in run
    self.check_smtp_login()
  File "/home/pi/urlwatch/lib/urlwatch/command.py", line 275, in check_smtp_login
    if have_password(smtp_hostname, smtp_username):
  File "/home/pi/urlwatch/lib/urlwatch/mailer.py", line 114, in have_password
    return keyring.get_password(smtp_server, from_email) is not None
  File "/home/pi/.local/lib/python3.5/site-packages/keyring/core.py", line 57, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/home/pi/.local/lib/python3.5/site-packages/keyring/backends/chainer.py", line 46, in get_password
    password = keyring.get_password(service, username)
  File "/home/pi/.local/lib/python3.5/site-packages/keyring/backends/SecretService.py", line 64, in get_password
    collection = self.get_preferred_collection()
  File "/home/pi/.local/lib/python3.5/site-packages/keyring/backends/SecretService.py", line 54, in get_preferred_collection
    raise InitError("Failed to create the collection: %s." % e)
keyring.errors.InitError: Failed to create the collection: Prompt dismissed..
`

**Comment by JsBergbau** [comment]
Problem seems plugin uses the wrong path
```
2019-01-21 16:19:27: charts.d: WARNING: main: Configuration file '/usr/local/lib/netdata/conf.d/charts.d.conf' not found.
2019-01-21 16:19:27: charts.d: WARNING: main: Configuration file '/usr/local/etc/netdata/charts.d.conf' not found.
Few lines later it says sensors is disabled, of course, config file in /etc/netdata/charts.d.conf where also netdata.conf is, seems not to be used.
```

**Comment by thp** [comment]
There is now an option to skip the keyring when using SMTP login:
https://urlwatch.readthedocs.io/en/latest/reporters.html#smtp-login-without-keyring

Also, you can install https://pypi.org/project/keyrings.alt/ as an alternative to skip the D-Bus service discovery.
