### ISSUE TITLE
404 Client Error

### ISSUE THREAD

**Issue by spvkgn** [thp/urlwatch#352]
Could anyone help to find out why 404 error occurs? The url opens well with browser.
```
$ cat ~/.config/urlwatch/urls.yaml
kind: url
name: RN6Pro_3-32
url: https://pandao.ru/product/751adf5b-306d-4ca8-bed1-7733219f992f
filter: element-by-tag:title
```
```
$ urlwatch
===========================================================================
01. ERROR: RN6Pro_3-32
===========================================================================

---------------------------------------------------------------------------
ERROR: RN6Pro_3-32 (https://pandao.ru/product/751adf5b-306d-4ca8-bed1-7733219f992f)
---------------------------------------------------------------------------
404 Client Error: Not Found for url: https://pandao.ru/product/751adf5b-306d-4ca8-bed1-7733219f992f
---------------------------------------------------------------------------


--
urlwatch 2.15, Copyright 2008-2018 Thomas Perl
Website: https://thp.io/2008/urlwatch/
watched 1 URLs in 0 seconds
```

**Comment by spvkgn** [comment]
Tried with `ignore_http_error_codes: 404` but same error occurs. Is it possible to ignore this 404 error?

**Comment by cfbao** [comment]
`ignore_http_error_codes` is a new feature that hasn't been released yet. The `urlwatch` you have on your computer most probably doesn't support it yet.

**Comment by spvkgn** [comment]
Thanks, tried to uninstall `urlwatch` and install from master branch. Though it seems it's not working with  `ignore_http_error_codes: 404` as well:
```
$ urlwatch -v
2019-01-27 10:41:01,609 urlwatch INFO: turning on verbose logging mode
2019-01-27 10:41:01,618 minidb DEBUG: PRAGMA table_info(CacheEntry)
2019-01-27 10:41:01,619 minidb DEBUG: CREATE TABLE CacheEntry (id INTEGER PRIMARY KEY, guid TEXT, timestamp INTEGER, data TEXT, tries INTEGER, etag TEXT)
2019-01-27 10:41:01,689 main INFO: Using /home/pavel/.config/urlwatch/urls.yaml as URLs file
2019-01-27 10:41:01,689 main INFO: Using /home/pavel/.config/urlwatch/hooks.py for hooks
2019-01-27 10:41:01,689 main INFO: Using /home/pavel/.cache/urlwatch/cache.db as cache database
2019-01-27 10:41:01,690 main INFO: Found 1 jobs
2019-01-27 10:41:01,691 worker DEBUG: Processing 1 jobs
2019-01-27 10:41:01,692 handler INFO: Processing: <url url='https://pandao.ru/product/751adf5b-306d-4ca8-bed1-7733219f992f' ignore_http_error_codes=404 name='RN6Pro_3-32' filter='element-by-tag:title'>
2019-01-27 10:41:01,693 minidb DEBUG: SELECT data, timestamp, tries, etag FROM CacheEntry WHERE guid = ? ORDER BY timestamp DESC, tries DESC LIMIT ? ['3657a6b6f2b6c45b5effa987f32b495959ee0bbc', 1]
2019-01-27 10:41:01,697 connectionpool DEBUG: Starting new HTTPS connection (1): pandao.ru:443
2019-01-27 10:41:01,943 connectionpool DEBUG: https://pandao.ru:443 "GET /product/751adf5b-306d-4ca8-bed1-7733219f992f HTTP/1.1" 404 None
2019-01-27 10:41:01,948 worker DEBUG: Job finished: <url url='https://pandao.ru/product/751adf5b-306d-4ca8-bed1-7733219f992f' method='GET' ignore_http_error_codes=404 name='RN6Pro_3-32' filter='element-by-tag:title'>
2019-01-27 10:41:01,949 worker DEBUG: Using max_tries of 0 for <url url='https://pandao.ru/product/751adf5b-306d-4ca8-bed1-7733219f992f' method='GET' ignore_http_error_codes=404 name='RN6Pro_3-32' filter='element-by-tag:title'>
2019-01-27 10:41:01,949 worker INFO: Error while executing job <url url='https://pandao.ru/product/751adf5b-306d-4ca8-bed1-7733219f992f' method='GET' ignore_http_error_codes=404 name='RN6Pro_3-32' filter='element-by-tag:title'> ignored due to job config
2019-01-27 10:41:01,949 reporters INFO: Submitting with stdout (<class 'urlwatch.reporters.StdoutReporter'>)
2019-01-27 10:41:01,951 minidb DEBUG: VACUUM

$ urlwatch --test-filter 1
Traceback (most recent call last):
  File "/home/pavel/.local/bin/urlwatch", line 111, in <module>
    urlwatch_command.run()
  File "/home/pavel/.local/lib/python3.6/site-packages/urlwatch/command.py", line 293, in run
    self.handle_actions()
  File "/home/pavel/.local/lib/python3.6/site-packages/urlwatch/command.py", line 179, in handle_actions
    sys.exit(self.test_filter())
  File "/home/pavel/.local/lib/python3.6/site-packages/urlwatch/command.py", line 133, in test_filter
    raise job_state.exception
  File "/home/pavel/.local/lib/python3.6/site-packages/urlwatch/handler.py", line 74, in process
    data = self.job.retrieve(self)
  File "/home/pavel/.local/lib/python3.6/site-packages/urlwatch/jobs.py", line 264, in retrieve
    response.raise_for_status()
  File "/home/pavel/.local/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pandao.ru/product/751adf5b-306d-4ca8-bed1-7733219f992f
```
