### ISSUE TITLE
It totally ignores any filter

### ISSUE THREAD

**Issue by mihalycsaba** [thp/urlwatch#389]
I run urlwatch --edit and have the url tag and the filter tag in it only
if I change the url it changes the page that gets sent to my address, tried multiple filter examples from the readme, no change in the email output, it always sends the html not plain text. Tried out the html2text command in the shell and it works it converts it to plain text.
Email is set to send unchanged too.

tried these 
`filter: html2text,grep:Current.*version,strip`
or
`filter: element-by-tag:body`

same html output

**Comment by mihalycsaba** [comment]
even tried this 
filter:
  - html2text: pyhtml2text

nothing, tried writing lynx, nothing

**Comment by mihalycsaba** [comment]
even tried this custom one from https://github.com/thp/urlwatch/issues/322
copied the one with the python class in hooks.py then added the custom filter to urls.yaml, gives the same output as before

**Comment by mihalycsaba** [comment]
and I ran pip install html2text it's installed

**Comment by nille02** [comment]
How does your urls.yaml or url entry looks like?

**Comment by mihalycsaba** [comment]
cat /root/.config/urlwatch/urls.yaml
url: https://thp.io/2008/urlwatch/
filter: html2text

**Comment by nille02** [comment]
it worked for me. you can try to launch urlwatch with --verbose

**Comment by mihalycsaba** [comment]
```
[root@localhost urlwatch]# urlwatch --verbose
2019-04-26 16:56:13,219 urlwatch INFO: turning on verbose logging mode
2019-04-26 16:56:13,229 minidb DEBUG: PRAGMA table_info(CacheEntry)
2019-04-26 16:56:13,230 main INFO: Using /root/.config/urlwatch/urls.yaml as URLs file
2019-04-26 16:56:13,230 main INFO: Using /root/.config/urlwatch/hooks.py for hooks
2019-04-26 16:56:13,230 main INFO: Using /root/.cache/urlwatch/cache.db as cache database
2019-04-26 16:56:13,230 util INFO: Registering <class 'hooks.CustomMatchUrlFilter'>
2019-04-26 16:56:13,231 util INFO: Registering <class 'hooks.CustomRegexMatchUrlFilter'>
2019-04-26 16:56:13,231 util INFO: Registering <class 'hooks.CustomTextFileReporter'> as custom_file
2019-04-26 16:56:13,231 util INFO: Registering <class 'hooks.CustomHtmlFileReporter'> as custom_html
2019-04-26 16:56:13,232 main INFO: Found 1 jobs
2019-04-26 16:56:13,232 worker DEBUG: Processing 1 jobs
2019-04-26 16:56:13,233 handler INFO: Processing: <url url='https://thp.io/2008/urlwatch/' filter='html2text'>
2019-04-26 16:56:13,234 minidb DEBUG: SELECT data, timestamp, tries, etag FROM CacheEntry WHERE guid = ? ORDER BY timestamp DESC, tries DESC LIMIT ? ['5545f2b73c613bb02228f42413767c5aecac6a8e', 1]
2019-04-26 16:56:13,236 connectionpool DEBUG: Starting new HTTPS connection (1): thp.io:443
2019-04-26 16:56:13,624 connectionpool DEBUG: https://thp.io:443 "GET /2008/urlwatch/ HTTP/1.1" 304 0
2019-04-26 16:56:13,627 worker DEBUG: Job finished: <url url='https://thp.io/2008/urlwatch/' method='GET' filter='html2text'>
2019-04-26 16:56:13,627 worker DEBUG: Using max_tries of 0 for <url url='https://thp.io/2008/urlwatch/' method='GET' filter='html2text'>
2019-04-26 16:56:13,627 worker INFO: Job <url url='https://thp.io/2008/urlwatch/' method='GET' filter='html2text'> has not changed (HTTP 304)
2019-04-26 16:56:13,627 handler DEBUG: Got exception while processing <url url='https://thp.io/2008/urlwatch/' method='GET' filter='html2text'>
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urlwatch/handler.py", line 78, in process
    data = self.job.retrieve(self)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urlwatch/jobs.py", line 276, in retrieve
    raise NotModifiedError()
urlwatch.jobs.NotModifiedError
2019-04-26 16:56:13,627 reporters INFO: Submitting with stdout (<class 'urlwatch.reporters.StdoutReporter'>)
===========================================================================
01. UNCHANGED: https://thp.io/2008/urlwatch/
```

**Comment by mihalycsaba** [comment]
it throws some error, I don't know enough python to know what it means. Also I'm using centos7 with python36 from the scl repository

**Comment by nille02** [comment]
its not an error. he tells you that the site has not changed from the HTTP Status Code. in `urlwatch --test-filter 1` you should see the actual result. for a quick test, you can rename ~/.cache/urlwatch/cache.db to something else and run urlwatch again.

**Comment by mihalycsaba** [comment]
yes I got that part, but the output is in html here is the rest from this command

```
---------------------------------------------------------------------------
UNCHANGED: https://thp.io/2008/urlwatch/
---------------------------------------------------------------------------
<!DOCTYPE html>
<html>
<head>
  <title>urlwatch monitors webpages for you (thp.io)</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="initial-scale=1.0"/>
  <meta name="theme-color" content="#292d20">
  <link rel="stylesheet" type="text/css" href="/2015/archive/revisited.css">
</head>
<body>
<div id="root">

  <p id="breadcrumbs">
    <a href="/">thp.io</a> ·
    <a href="/2008/">2008</a> ·
    <span id="here">urlwatch</span>
  </p>

<div id="content">

      <h1>urlwatch monitors webpages for you</h1>
      <p>
      urlwatch is intended to help you watch changes in webpages and get notified
      (via e-mail, in your terminal or through various third party services) of any
      changes. The change notification will include the URL that has changed and
      a unified diff of what has changed.
      </p>
      <p>
      urlwatch is open source under a <a href="https://github.com/thp/urlwatch/blob/master/COPYING">BSD-style license</a>.
      </p>

      <h2>Features</h2>
      <ul>
          <li>Extensible YAML-based configuration file, <a href="/2010/minidb/">minidb</a>-based cache</li>
          <li>Uses Concurrent downloads and <code>If-Modified-Since</code> for speed</li>
          <li>Support for using HTTP POST with data and custom HTTP methods</li>
          <li>Convert HTML to plaintext using lynx, html2text or a regex</li>
          <li>Watch output of shell commands, create custom job types</li>
          <li>Wide range of built-in filters, and support for writing your own</li>
          <li>Send changes via e-mail, optionally also as HTML</li>
          <li>Colored diff output on the console (can be turned off)</li>
          <li>Sends a proper <a href="info.html">User-agent header</a></li>
      </ul>

      <h2>Installation</h2>

      <p>
      If you have Python 3 and pip (the Python package manager) installed, you can
      install the latest version and its dependencies using the following command:
      </p>

      <pre>pip3 install --upgrade urlwatch</pre>

      <h2>Download</h2>

      <ul>
          <li><strong>Current version</strong>: <a href="https://github.com/thp/urlwatch/archive/2.17.tar.gz">urlwatch-2.17.tar.gz</a> (2019-04-12)</li>
      </ul>
      <ul>
          <li><strong>Git:</strong> <a href="https://github.com/thp/urlwatch">github.com/thp/urlwatch</a></li>
          <li><strong>PyPI:</strong> <a href="http://pypi.python.org/pypi/urlwatch">urlwatch</a></li>
          <li>..or check out <a href="https://repology.org/metapackage/urlwatch/versions">urlwatch in Linux distributions</a></li>
      </ul>

</div>

  <address>
    <a href="/about">Thomas Perl</a> ·
    <span id="last-updated">2019-04-12</span>
  </address>

</div>
</body>
</html>

---------------------------------------------------------------------------


--
urlwatch 2.17, Copyright 2008-2019 Thomas Perl
Website: https://thp.io/2008/urlwatch/
watched 1 URLs in 0 seconds
2019-04-26 16:56:13,628 reporters INFO: Submitting with email (<class 'urlwatch.reporters.EMailReporter'>)
2019-04-26 16:56:15,054 minidb DEBUG: VACUUM

```

**Comment by nille02** [comment]
can you post the complete output with --verbose?

**Comment by mihalycsaba** [comment]
```
[root@localhost urlwatch]# urlwatch --verbose
2019-04-26 17:10:03,578 urlwatch INFO: turning on verbose logging mode
2019-04-26 17:10:03,587 minidb DEBUG: PRAGMA table_info(CacheEntry)
2019-04-26 17:10:03,589 main INFO: Using /root/.config/urlwatch/urls.yaml as URLs file
2019-04-26 17:10:03,589 main INFO: Using /root/.config/urlwatch/hooks.py for hooks
2019-04-26 17:10:03,589 main INFO: Using /root/.cache/urlwatch/cache.db as cache database
2019-04-26 17:10:03,590 util INFO: Registering <class 'hooks.CustomMatchUrlFilter'>
2019-04-26 17:10:03,590 util INFO: Registering <class 'hooks.CustomRegexMatchUrlFilter'>
2019-04-26 17:10:03,591 util INFO: Registering <class 'hooks.CustomTextFileReporter'> as custom_file
2019-04-26 17:10:03,591 util INFO: Registering <class 'hooks.CustomHtmlFileReporter'> as custom_html
2019-04-26 17:10:03,592 main INFO: Found 1 jobs
2019-04-26 17:10:03,592 worker DEBUG: Processing 1 jobs
2019-04-26 17:10:03,592 handler INFO: Processing: <url url='https://thp.io/2008/urlwatch/' filter='html2text'>
2019-04-26 17:10:03,593 minidb DEBUG: SELECT data, timestamp, tries, etag FROM CacheEntry WHERE guid = ? ORDER BY timestamp DESC, tries DESC LIMIT ? ['5545f2b73c613bb02228f42413767c5aecac6a8e', 1]
2019-04-26 17:10:03,596 connectionpool DEBUG: Starting new HTTPS connection (1): thp.io:443
2019-04-26 17:10:04,020 connectionpool DEBUG: https://thp.io:443 "GET /2008/urlwatch/ HTTP/1.1" 304 0
2019-04-26 17:10:04,022 worker DEBUG: Job finished: <url url='https://thp.io/2008/urlwatch/' method='GET' filter='html2text'>
2019-04-26 17:10:04,023 worker DEBUG: Using max_tries of 0 for <url url='https://thp.io/2008/urlwatch/' method='GET' filter='html2text'>
2019-04-26 17:10:04,023 worker INFO: Job <url url='https://thp.io/2008/urlwatch/' method='GET' filter='html2text'> has not changed (HTTP 304)
2019-04-26 17:10:04,023 handler DEBUG: Got exception while processing <url url='https://thp.io/2008/urlwatch/' method='GET' filter='html2text'>
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urlwatch/handler.py", line 78, in process
    data = self.job.retrieve(self)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/urlwatch/jobs.py", line 276, in retrieve
    raise NotModifiedError()
urlwatch.jobs.NotModifiedError
2019-04-26 17:10:04,023 reporters INFO: Submitting with stdout (<class 'urlwatch.reporters.StdoutReporter'>)
===========================================================================
01. UNCHANGED: https://thp.io/2008/urlwatch/
===========================================================================

---------------------------------------------------------------------------
UNCHANGED: https://thp.io/2008/urlwatch/
---------------------------------------------------------------------------
<!DOCTYPE html>
<html>
<head>
  <title>urlwatch monitors webpages for you (thp.io)</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="viewport" content="initial-scale=1.0"/>
  <meta name="theme-color" content="#292d20">
  <link rel="stylesheet" type="text/css" href="/2015/archive/revisited.css">
</head>
<body>
<div id="root">

  <p id="breadcrumbs">
    <a href="/">thp.io</a> ·
    <a href="/2008/">2008</a> ·
    <span id="here">urlwatch</span>
  </p>

<div id="content">

      <h1>urlwatch monitors webpages for you</h1>
      <p>
      urlwatch is intended to help you watch changes in webpages and get notified
      (via e-mail, in your terminal or through various third party services) of any
      changes. The change notification will include the URL that has changed and
      a unified diff of what has changed.
      </p>
      <p>
      urlwatch is open source under a <a href="https://github.com/thp/urlwatch/blob/master/COPYING">BSD-style license</a>.
      </p>

      <h2>Features</h2>
      <ul>
          <li>Extensible YAML-based configuration file, <a href="/2010/minidb/">minidb</a>-based cache</li>
          <li>Uses Concurrent downloads and <code>If-Modified-Since</code> for speed</li>
          <li>Support for using HTTP POST with data and custom HTTP methods</li>
          <li>Convert HTML to plaintext using lynx, html2text or a regex</li>
          <li>Watch output of shell commands, create custom job types</li>
          <li>Wide range of built-in filters, and support for writing your own</li>
          <li>Send changes via e-mail, optionally also as HTML</li>
          <li>Colored diff output on the console (can be turned off)</li>
          <li>Sends a proper <a href="info.html">User-agent header</a></li>
      </ul>

      <h2>Installation</h2>

      <p>
      If you have Python 3 and pip (the Python package manager) installed, you can
      install the latest version and its dependencies using the following command:
      </p>

      <pre>pip3 install --upgrade urlwatch</pre>

      <h2>Download</h2>

      <ul>
          <li><strong>Current version</strong>: <a href="https://github.com/thp/urlwatch/archive/2.17.tar.gz">urlwatch-2.17.tar.gz</a> (2019-04-12)</li>
      </ul>
      <ul>
          <li><strong>Git:</strong> <a href="https://github.com/thp/urlwatch">github.com/thp/urlwatch</a></li>
          <li><strong>PyPI:</strong> <a href="http://pypi.python.org/pypi/urlwatch">urlwatch</a></li>
          <li>..or check out <a href="https://repology.org/metapackage/urlwatch/versions">urlwatch in Linux distributions</a></li>
      </ul>

</div>

  <address>
    <a href="/about">Thomas Perl</a> ·
    <span id="last-updated">2019-04-12</span>
  </address>

</div>
</body>
</html>

---------------------------------------------------------------------------


--
urlwatch 2.17, Copyright 2008-2019 Thomas Perl
Website: https://thp.io/2008/urlwatch/
watched 1 URLs in 0 seconds
2019-04-26 17:10:04,024 reporters INFO: Submitting with email (<class 'urlwatch.reporters.EMailReporter'>)
2019-04-26 17:10:05,613 minidb DEBUG: VACUUM

```

**Comment by nille02** [comment]
and `urlwatch --test-filter 1 --verbose`

**Comment by mihalycsaba** [comment]
ok this one works, why doesnt it gets into the email?
```
[root@localhost urlwatch]# urlwatch --test-filter 1 --verbose
2019-04-26 17:14:27,328 urlwatch INFO: turning on verbose logging mode
2019-04-26 17:14:27,337 minidb DEBUG: PRAGMA table_info(CacheEntry)
2019-04-26 17:14:27,338 main INFO: Using /root/.config/urlwatch/urls.yaml as URLs file
2019-04-26 17:14:27,338 main INFO: Using /root/.config/urlwatch/hooks.py for hooks
2019-04-26 17:14:27,338 main INFO: Using /root/.cache/urlwatch/cache.db as cache database
2019-04-26 17:14:27,338 util INFO: Registering <class 'hooks.CustomMatchUrlFilter'>
2019-04-26 17:14:27,339 util INFO: Registering <class 'hooks.CustomRegexMatchUrlFilter'>
2019-04-26 17:14:27,339 util INFO: Registering <class 'hooks.CustomTextFileReporter'> as custom_file
2019-04-26 17:14:27,339 util INFO: Registering <class 'hooks.CustomHtmlFileReporter'> as custom_html
2019-04-26 17:14:27,340 main INFO: Found 1 jobs
2019-04-26 17:14:27,340 handler INFO: Processing: <url url='https://thp.io/2008/urlwatch/' ignore_cached=True filter='html2text'>
2019-04-26 17:14:27,341 minidb DEBUG: SELECT data, timestamp, tries, etag FROM CacheEntry WHERE guid = ? ORDER BY timestamp DESC, tries DESC LIMIT ? ['5545f2b73c613bb02228f42413767c5aecac6a8e', 1]
2019-04-26 17:14:27,343 connectionpool DEBUG: Starting new HTTPS connection (1): thp.io:443
2019-04-26 17:14:28,133 connectionpool DEBUG: https://thp.io:443 "GET /2008/urlwatch/ HTTP/1.1" 200 1242
2019-04-26 17:14:28,135 filters DEBUG: Matching <hooks.CustomMatchUrlFilter object at 0x7f71bd705b70> with <url url='https://thp.io/2008/urlwatch/' method='GET' ignore_cached=True filter='html2text'> result: False
2019-04-26 17:14:28,135 filters DEBUG: Matching <hooks.CustomRegexMatchUrlFilter object at 0x7f71bd705438> with <url url='https://thp.io/2008/urlwatch/' method='GET' ignore_cached=True filter='html2text'> result: False
2019-04-26 17:14:28,135 filters INFO: Applying filter 'html2text', subfilter None to https://thp.io/2008/urlwatch/
  urlwatch monitors webpages for you (thp.io)
    thp.io ·
    2008 ·
    urlwatch
      urlwatch monitors webpages for you
      urlwatch is intended to help you watch changes in webpages and get notified
      (via e-mail, in your terminal or through various third party services) of any
      changes. The change notification will include the URL that has changed and
      a unified diff of what has changed.
      urlwatch is open source under a BSD-style license.
      Features
          Extensible YAML-based configuration file, minidb-based cache
          Uses Concurrent downloads and If-Modified-Since for speed
          Support for using HTTP POST with data and custom HTTP methods
          Convert HTML to plaintext using lynx, html2text or a regex
          Watch output of shell commands, create custom job types
          Wide range of built-in filters, and support for writing your own
          Send changes via e-mail, optionally also as HTML
          Colored diff output on the console (can be turned off)
          Sends a proper User-agent header
      Installation
      If you have Python 3 and pip (the Python package manager) installed, you can
      install the latest version and its dependencies using the following command:
      pip3 install --upgrade urlwatch
      Download
          Current version: urlwatch-2.17.tar.gz (2019-04-12)
          Git: github.com/thp/urlwatch
          PyPI: urlwatch
          ..or check out urlwatch in Linux distributions
    Thomas Perl ·
    2019-04-12

```

**Comment by mihalycsaba** [comment]
could my email configs affect it?

**Comment by nille02** [comment]
like i say previously. the page did not changed. he guess this from the http status code. your last version was the full page. if you delete or rename the cache.db file in ~/.cache/urlwatch he makes a uncached requests and send you a mail. or if you wait long enough that.

**Comment by mihalycsaba** [comment]
ok so if something changes, it will only print the diff? It confused me that it sends the html code even if it's unchanged, I turned on the unchanged tag in the config, I guessed that the unchanged email would apply the filter regardless.
Thank you very much for your time.

**Comment by nille02** [comment]
if something is changed he print the diff and send you a mail if you had enabled it. 

> I turned on the unchanged tag in the config, 

with this he send you a mail even if nothing changed. And he send you its last version.

**Comment by mihalycsaba** [comment]
Yes, I understood the unchanged's purpose, I just don't understand why it didn't applied the filter on the output anyway, instead of sending me the html code.

**Comment by nille02** [comment]
Because the filter is only applied if something changed. The website report that there is no change since our last visit. For urlwatch is nothing to do in this case. If you enable that he has to report even if nothing changed, he reports/sends you the last data in its cache. In your case its the not filtered data. 

your case happens if you check a url and change or add a filter afterwards. The new filter is only applied if something on the website changed.

**Comment by mihalycsaba** [comment]
Understood, thank you for your time, hopefully this helps some brickhead like me, closing it now.

**Comment by thp** [comment]
For completeness sake, here's how filtering works currently and why this behavior is seen:

- When a page is first added, the filter that is set at that point gets applied and the filtered result saved in the database (if there's no filter at the time it is first added, the HTML source of a page is saved)
- Retrieving the page is done conditionally (meaning if the server says the page hasn't been modified, it isn't even retrieved, and considered unchanged) -- in that case, even if you change the filter, the filter will not get applied (we cannot re-apply the filter, since the data that is stored is the filtered output from the previous run, and we would filter twice)
- Once the page changes on the server, the new fillter will be applied, the old content (with old filter) will be the "old" state of the diff and the "new" state of the diff will be the new content with new filter applied

In theory we could in a future version or with an optional flag make it so that we always store the unfiltered content and re-apply the most recent filter, which would be great (and more flexible) but also has some drawbacks:

- Changing the filter might not cause any differences if the things that change are filtered out
- If the filter is "broken" (filters too much), then it will filter too much in both the old output and the new output
- There would be a one-time migration thing where differences can't be detected while we save the new source HTML in the database (this could be worked around a bit, though)

For this reason, the `--test-filter` feature was added, so the filter can always be tested with the current page content (doing an unconditional request).

The edge case that we see here has to do with the `display` option `unchanged: true`, which will always output the old filtered data (old content filtered with old filter) and the new filter isn't applied at all.

**Comment by thp** [comment]
I tried to also clarify this to the documentation now, see d0f7ab2e19296f59bae3b40d66aefabb6dfa1dce.
