### ISSUE TITLE
Job fails with multiple filters (simple and with subfilters)

### ISSUE THREAD

**Issue by tomaszn** [thp/urlwatch#413]
I'd like to apply two filters:
```filter:
  - css:
          selector: body
          exclude: 'style,script'
  - html2text
```
When running `urlwatch --test-filter 1` I get:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/urlwatch", line 111, in <module>
    urlwatch_command.run()
  File "/home/user/.local/pipx/venvs/urlwatch/lib/python3.6/site-packages/urlwatch/command.py", line 293, in run
    self.handle_actions()
  File "/home/user/.local/pipx/venvs/urlwatch/lib/python3.6/site-packages/urlwatch/command.py", line 179, in handle_actions
    sys.exit(self.test_filter())
  File "/home/user/.local/pipx/venvs/urlwatch/lib/python3.6/site-packages/urlwatch/command.py", line 133, in test_filter
    raise job_state.exception
  File "/home/user/.local/pipx/venvs/urlwatch/lib/python3.6/site-packages/urlwatch/handler.py", line 92, in process
    filter_kind, subfilter = key, item[key]
TypeError: string indices must be integers
```

**Comment by cfbao** [comment]
When writing filters in the list format, each filter must be a YAML map.
In your case, you should write
```yaml
  - css:
          selector: body
          exclude: 'style,script'
  - html2text: 
```

**Comment by tomaszn** [comment]
Thanks for your quick answer, it helped.
Is there a reason to enforce having only maps in such case?

**Comment by cfbao** [comment]
I didn't write this code. I guess it's just convenient to code like this.
It's not exactly "enforcing" rather than "only expecting" a particular form.

**Comment by thp** [comment]
YAML can't have a mix of key-value pairs and keys "only", this is why you have to write it like that. Of course, just having a "list of strings" is possible too, but it's not possible to mix'n'match.
