### ISSUE TITLE
yaml.scanner.ScannerError: mapping values are not allowed here   in "/home/aaron/.config/urlwatch/urls.yaml", line 2, column 4

### ISSUE THREAD

**Issue by aaronmweiss** [thp/urlwatch#439]
Getting the below output when I run this. I have the following in my urls.yaml file:

name:devawme
url: https://dev.aaronweiss.me
filter: element-by-id:footer-check

Not sure what I'm doing wrong.

```bash
aaron@maria_ubntu_default:~/.config/urlwatch$ urlwatch
Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 102, in <module>
    urlwatch = Urlwatch(command_config, config_storage, cache_storage, urls_storage)
  File "/home/aaron/.local/lib/python3.6/site-packages/urlwatch/main.py", line 66, in __init__
    self.load_jobs()
  File "/home/aaron/.local/lib/python3.6/site-packages/urlwatch/main.py", line 87, in load_jobs
    jobs = self.urls_storage.load_secure()
  File "/home/aaron/.local/lib/python3.6/site-packages/urlwatch/storage.py", line 251, in load_secure
    jobs = self.load()
  File "/home/aaron/.local/lib/python3.6/site-packages/urlwatch/storage.py", line 322, in load
    return [JobBase.unserialize(job) for job in yaml.load_all(fp, Loader=yaml.SafeLoader) if job is not None]
  File "/home/aaron/.local/lib/python3.6/site-packages/urlwatch/storage.py", line 322, in <listcomp>
    return [JobBase.unserialize(job) for job in yaml.load_all(fp, Loader=yaml.SafeLoader) if job is not None]
  File "/home/aaron/.local/lib/python3.6/site-packages/yaml/__init__.py", line 130, in load_all
    yield loader.get_data()
  File "/home/aaron/.local/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_data
    return self.construct_document(self.get_node())
  File "/home/aaron/.local/lib/python3.6/site-packages/yaml/composer.py", line 27, in get_node
    return self.compose_document()
  File "/home/aaron/.local/lib/python3.6/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/home/aaron/.local/lib/python3.6/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/home/aaron/.local/lib/python3.6/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/home/aaron/.local/lib/python3.6/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/home/aaron/.local/lib/python3.6/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/home/aaron/.local/lib/python3.6/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/home/aaron/.config/urlwatch/urls.yaml", line 2, column 4
```

**Comment by cfbao** [comment]
Put a whitespace after "name:". Yaml mappings require this whitespace.

**Comment by aaronmweiss** [comment]
That did work, but now I get this:
```
aaron@maria_ubntu_default:~/.config/urlwatch$ urlwatch
  File "/home/aaron/.local/bin/urlwatch", line 67
    ...
    ^
SyntaxError: invalid syntax
```

**Comment by thp** [comment]
You need to run it using Python 3, not Python 2.
