### ISSUE TITLE
Handling large emails

### ISSUE THREAD

**Issue by csill1634** [thp/urlwatch#45]
Hi!

after migrating to the new version, the second  run (after enabling htl2text for all my 300 urls) resulted in a large email that was rejected from the server: 

```
Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 376, in <module>
    main(parser.parse_args())
  File "/usr/bin/urlwatch", line 343, in main
    report.finish()
  File "/usr/lib/python3.5/site-packages/urlwatch/handler.py", line 128, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/usr/lib/python3.5/site-packages/urlwatch/reporters.py", line 81, in submit_all
    cls(report, cfg, job_states, duration).submit()
  File "/usr/lib/python3.5/site-packages/urlwatch/reporters.py", line 340, in submit
    mailer.send(msg)
  File "/usr/lib/python3.5/site-packages/urlwatch/mailer.py", line 65, in send
    s.sendmail(msg['From'], [msg['To']], msg.as_string())
  File "/usr/lib/python3.5/smtplib.py", line 857, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (552, b'5.2.3 Message size exceeds fixed maximum message size (15000000)', 'XXXXX@XXXX.com')
```

Maybe it is possible to split large emails into smaller parts?

Thanks!

**Comment by thp** [comment]
You could comment out a subset of your jobs, let urlwatch run and report the first changes, then uncomment some more and run it again and split it up like that. It's hard to figure our where and how to split the mails (it depends on the mail server's limits). And sending a new mail for all of your 300 subscriptions separately is probably also not something you'd like to see.

**Comment by thp** [comment]
Closing as WONTFIX -- we don't plan on having a SMTP-server-specific fix.
