### ISSUE TITLE
urlwatch 2.18 broke email delivery

### ISSUE THREAD

**Issue by jpiszcz** [thp/urlwatch#496]
Issue: urlwatch 2.x to 2.17 working without any issue for several months, upon upgrade to 2.18-1 email can no longer be sent.

I use postfix to relay to gmail (no password needed for email -> outbound via local smtp) and none of that has changed, only urlwatch was upgraded from 2.17 to 2.18.

Downgrading to urlwatch 2.17 fixes the issue.

```
$ dpkg -l | grep urlwatch
ii  urlwatch                             2.18-1                           all          monitors webpages for you

$ urlwatch
===========================================================================
01. NEW: XXXXXXXXXXXXXXXX1
02. NEW: XXXXXXXXXXXXXXXX2
===========================================================================

---------------------------------------------------------------------------
NEW: XXXXXXXXXXXXXXXX1 ( https://XXXXXXXXXXXXXXXX1/ )
---------------------------------------------------------------------------


---------------------------------------------------------------------------
NEW: XXXXXXXXXXXXXXXX2 ( https://XXXXXXXXXXXXXXXX2/ )
---------------------------------------------------------------------------


--
urlwatch 2.18, Copyright 2008-2020 Thomas Perl
Website: https://thp.io/2008/urlwatch/
watched 23 URLs in 1 seconds
Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 11, in <module>
    load_entry_point('urlwatch==2.18', 'console_scripts', 'urlwatch')()
  File "/usr/lib/python3/dist-packages/urlwatch/cli.py", line 111, in main
    urlwatch_command.run()
  File "/usr/lib/python3/dist-packages/urlwatch/command.py", line 299, in run
    self.urlwatcher.close()
  File "/usr/lib/python3/dist-packages/urlwatch/main.py", line 99, in close
    self.report.finish()
  File "/usr/lib/python3/dist-packages/urlwatch/handler.py", line 159, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/usr/lib/python3/dist-packages/urlwatch/reporters.py", line 113, in submit_all
    subclass(report, cfg, job_states, duration).submit()
  File "/usr/lib/python3/dist-packages/urlwatch/reporters.py", line 430, in submit
    mailer.send(msg)
  File "/usr/lib/python3/dist-packages/urlwatch/mailer.py", line 96, in send
    raise ValueError('No password available in keyring for {}, {}'.format(self.smtp_server, self.smtp_user))
ValueError: No password available in keyring for localhost, user@gmail.com

```

**Comment by schildbach** [comment]
I've got the same regression.

**Comment by scottmac** [comment]
The code between 2.17 and 2.18 looks logically the same.

Does anyone want to post the config that they have?

**Comment by mwerlen** [comment]
Hi,

I've had the same problem and adding `report/email/smtp/auth: false` solved
the problem.

Maxime

Le mar. 19 mai 2020 à 02:31, Scott MacVicar <notifications@github.com> a
écrit :

**Comment by schildbach** [comment]
Ah, indeed `auth: false` solves the problem. Seems like the default has changed.

**Comment by jpiszcz** [comment]
Thanks, fixes it here too!  The issue I had before this change is it would work from command line but not from cron, now it works from both with the new version.

Fix:
Edit: .config/urlwatch/urlwatch.yaml

Change:
```
    smtp:
      host: localhost
      keyring: false
      port: 25
      starttls: true
    subject: '{count} changes: {jobs}'
```

To:
```
    smtp:
      host: localhost
      auth: false
      keyring: false
      port: 25
      starttls: true
    subject: '{count} changes: {jobs}'

```

FYSA - Some further details about this issue did crop up in the past for documentation purposes:
https://github.com/thp/urlwatch/issues/260
https://mail.gnome.org/archives/gnome-keyring-list/2012-December/msg00001.html

**Comment by thp** [comment]
This was changed in #431, I've now updated the `CHANGELOG.md` in Git to account for this.

**Comment by thp** [comment]
Now also mentioned in https://urlwatch.readthedocs.io/en/latest/deprecated.html
