### ISSUE TITLE
error import url

### ISSUE THREAD

**Issue by marz-hunter** [thp/urlwatch#574]
./urlwatch --urls=listsubdomain.txt

`Traceback (most recent call last):
  File "./urlwatch", line 9, in <module>
    main()
  File "/home/recon/urlwatch/lib/urlwatch/cli.py", line 108, in main
    urlwatch = Urlwatch(command_config, config_storage, cache_storage, urls_storage)
  File "/home/recon/urlwatch/lib/urlwatch/main.py", line 66, in __init__
    self.load_jobs()
  File "/home/recon/urlwatch/lib/urlwatch/main.py", line 87, in load_jobs
    jobs = self.urls_storage.load_secure()
  File "/home/recon/urlwatch/lib/urlwatch/storage.py", line 285, in load_secure
    jobs = self.load()
  File "/home/recon/urlwatch/lib/urlwatch/storage.py", line 370, in load
    return [JobBase.unserialize(job) for job in yaml.load_all(fp, Loader=yaml.SafeLoader) if job is not None]
  File "/home/recon/urlwatch/lib/urlwatch/storage.py", line 370, in <listcomp>
    return [JobBase.unserialize(job) for job in yaml.load_all(fp, Loader=yaml.SafeLoader) if job is not None]
  File "/home/recon/urlwatch/lib/urlwatch/jobs.py", line 124, in unserialize
    raise ValueError('Kind is not specified, and no job matches: %r' % (data,))
ValueError: Kind is not specified, and no job matches: 'https://google.com https://microsoft.com'`

**Comment by thp** [comment]
`--urls=` takes a YAML file that describes the job list, not any arbitrary file. Maybe what you want to do is:

```bash
(
while read url; do
    urlwatch --add url=$url
done
) < listsubdomain.txt
```

**Comment by marz-hunter** [comment]
thanks for the answer, this is successfully done
