### ISSUE TITLE
--edit-hooks produces an error

### ISSUE THREAD

**Issue by cjohnsonuk** [thp/urlwatch#578]
I've added the line  `__no_subfilter__ = True ` to my `hooks.py` to fix an issue in another ticket

but when I run `urlwatch --edit-hooks` I get this 
```
urlwatch --edit-hooks
Traceback (most recent call last):
  File "/bin/urlwatch", line 107, in <module>
    urlwatch = Urlwatch(command_config, config_storage, cache_storage, urls_storage)
  File "/usr/local/lib/python3.6/site-packages/urlwatch/main.py", line 66, in __init__
    self.load_jobs()
  File "/usr/local/lib/python3.6/site-packages/urlwatch/main.py", line 87, in load_jobs
    jobs = self.urls_storage.load_secure()
  File "/usr/local/lib/python3.6/site-packages/urlwatch/storage.py", line 303, in load_secure
    if shelljob_errors and any(is_shell_job(job) for job in jobs):
  File "/usr/local/lib/python3.6/site-packages/urlwatch/storage.py", line 303, in <genexpr>
    if shelljob_errors and any(is_shell_job(job) for job in jobs):
  File "/usr/local/lib/python3.6/site-packages/urlwatch/storage.py", line 291, in is_shell_job
    for filter_kind, subfilter in FilterBase.normalize_filter_list(job.filter):
  File "/usr/local/lib/python3.6/site-packages/urlwatch/filters.py", line 95, in normalize_filter_list
    raise ValueError('Unknown filter kind: {} (subfilter {})'.format(filter_kind, subfilter))
ValueError: Unknown filter kind: tosentences (subfilter {})
```
Let me know which files details will help diagnose this.

**Comment by thp** [comment]
This should only happen in cases where the security checks (world-writable / group-writable) are hit. By changing the file mode of your `urls.yaml` to `0o600` (e.g. `chmod 600 /path/to/urls.yaml`) the security check should not be done.

**Comment by cjohnsonuk** [comment]
This fixed it!  Thank you!!
