### ISSUE TITLE
Don't create .config directory if not needed

### ISSUE THREAD

**Issue by schildbach** [thp/urlwatch#594]
I'm trying to run urlwatch on a read-only filesystem (docker container), with only cache.db mapped to a writable volume. However, urlwatch tries to create `~/.config` and fails.

```
urlwatch_1  | crond: USER root pid  34 cmd cd /root && urlwatch --urls urls.yaml --config urlwatch.yaml --hooks hooks.py --cache /tmp/cache.db
urlwatch_1  | Traceback (most recent call last):
urlwatch_1  |   File "/usr/bin/urlwatch", line 11, in <module>
urlwatch_1  |     load_entry_point('urlwatch==2.21', 'console_scripts', 'urlwatch')()
urlwatch_1  |   File "/usr/lib/python3.8/site-packages/urlwatch/cli.py", line 108, in main
urlwatch_1  |     urlwatch = Urlwatch(command_config, config_storage, cache_storage, urls_storage)
urlwatch_1  |   File "/usr/lib/python3.8/site-packages/urlwatch/main.py", line 57, in __init__
urlwatch_1  |     self.check_directories()
urlwatch_1  |   File "/usr/lib/python3.8/site-packages/urlwatch/main.py", line 73, in check_directories
urlwatch_1  |     os.makedirs(self.urlwatch_config.urlwatch_dir)
urlwatch_1  |   File "/usr/lib/python3.8/os.py", line 213, in makedirs
urlwatch_1  |     makedirs(head, exist_ok=exist_ok)
urlwatch_1  |   File "/usr/lib/python3.8/os.py", line 223, in makedirs
urlwatch_1  |     mkdir(name, mode)
urlwatch_1  | OSError: [Errno 30] Read-only file system: '/root/.config'
```

My proposal is to make urlwatch not write if it doesn't need to.

**Comment by mborsetti** [comment]
This fix is in the unreleased branch of the fork called `webchanges` at https://github.com/mborsetti/webchanges/tree/unreleased

`pip install git+https://github.com/mborsetti/webchanges.git@unreleased`
