### ISSUE TITLE
urlwatch fails to use keyring when running from cron

### ISSUE THREAD

**Issue by ondrejj** [thp/urlwatch#603]
Daily run from cron started to throw this backtrace:

```
Traceback (most recent call last):
  File "/bin/urlwatch", line 33, in <module>
    sys.exit(load_entry_point('urlwatch==2.21', 'console_scripts',
'urlwatch')())
  File "/usr/lib/python3.9/site-packages/urlwatch/cli.py", line 112, in main
    urlwatch_command.run()
  File "/usr/lib/python3.9/site-packages/urlwatch/command.py", line 404, in run
    self.urlwatcher.close()
  File "/usr/lib/python3.9/site-packages/urlwatch/main.py", line 99, in close
    self.report.finish()
  File "/usr/lib/python3.9/site-packages/urlwatch/handler.py", line 205, in
finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/usr/lib/python3.9/site-packages/urlwatch/reporters.py", line 120, in
submit_all
    subclass(report, cfg, job_states, duration).submit()
  File "/usr/lib/python3.9/site-packages/urlwatch/reporters.py", line 415, in
submit
    mailer.send(msg)
  File "/usr/lib/python3.9/site-packages/urlwatch/mailer.py", line 96, in send
    raise ValueError('No password available in keyring for {}, {}'
ValueError: No password available in keyring for localhost, urlwatch@localhost
```

Using urlwatch-2.21-1.fc33.noarch on Fedora 33.

Switch from smtp to sendmail woks as a workaround, but may be this should be fixed.
My smtp settings:

```
    method: smtp
    sendmail:
      path: sendmail
    smtp:
      host: localhost
      keyring: false
      port: 25
      starttls: true
```

My SMTP server accepts email without password from localhost clients.

**Comment by thp** [comment]
If you do have an SMTP server running, please use this. There are ways to force cron to be able to access your keychain, but it's not good security practice, especially if you already have the alternative of an SMTP server running.
