### ISSUE TITLE
2.22: Cannot use same url in multiple jobs

### ISSUE THREAD

**Issue by jpdsceu** [thp/urlwatch#607]
Since version 2.22, I get below error if there are 2 of the same urls in different jobs in urls.yaml.
Error:

```
Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 11, in <module>
    load_entry_point('urlwatch==2.22', 'console_scripts', 'urlwatch')()
  File "/usr/lib/python3.8/site-packages/urlwatch/cli.py", line 108, in main
    urlwatch = Urlwatch(command_config, config_storage, cache_storage, urls_storage)
  File "/usr/lib/python3.8/site-packages/urlwatch/main.py", line 66, in __init__
    self.load_jobs()
  File "/usr/lib/python3.8/site-packages/urlwatch/main.py", line 85, in load_jobs
    jobs = self.urls_storage.load_secure()
  File "/usr/lib/python3.8/site-packages/urlwatch/storage.py", line 305, in load_secure
    jobs = self.load()
  File "/usr/lib/python3.8/site-packages/urlwatch/storage.py", line 407, in load
    return self._parse(fp)
  File "/usr/lib/python3.8/site-packages/urlwatch/storage.py", line 386, in _parse
    raise ValueError('\n   '.join(['Each job must have a unique URL, append #1, #2, ... to make them unique:']
ValueError: Each job must have a unique URL, append #1, #2, ... to make them unique:
   https://videocardz.com/sections/drivers
```

urls.yaml
```
---
name: "\U0001F7E2 NVIDIA GEFORCE Game Ready Drivers update"
url: "https://videocardz.com/sections/drivers"
ignore_connection_errors: true
ignore_http_error_codes: 4xx, 5xx
timeout: 10
filter:
    - xpath: (//body[contains(@class,'archive')]/section//div[@class='relatedblock']/a[contains(@class,'clearfix')]/div[@class='related-text'])[11]
    - html2text: re
---
name: "\U0001F7E2 AMD Radeon Adrenalin Edition driver update"
url: "https://videocardz.com/sections/drivers"
ignore_connection_errors: true
ignore_http_error_codes: 4xx, 5xx
timeout: 10
filter:
    - xpath: (//body[contains(@class,'archive')]/section//div[@class='relatedblock']/a[contains(@class,'clearfix')]/div[@class='related-text'])[1]
    - html2text: re
```

Is there a new way to handle multiple of the same urls in different jobs?

Thank you.

**Comment by cfbao** [comment]
It's not supported. A workaround is to use the anchor hack:
https://github.com/thp/urlwatch/issues/232
https://github.com/thp/urlwatch/issues/153

**Comment by jpdsceu** [comment]
Thank you :-)
