### ISSUE TITLE
Telegram reporter is broken: TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by ramelito** [thp/urlwatch#610]
I am using telegram reporter, i have chat id in telegram chats, but i am getting error when reporter is invoked:

Traceback (most recent call last):
  File "./urlwatch", line 9, in <module>
    main()
  File "/urlwatch/lib/urlwatch/cli.py", line 112, in main
    urlwatch_command.run()
  File "/urlwatch/lib/urlwatch/command.py", line 407, in run
    self.check_test_reporter()
  File "/urlwatch/lib/urlwatch/command.py", line 313, in check_test_reporter
    report.finish_one(name)
  File "/urlwatch/lib/urlwatch/handler.py", line 218, in finish_one
    ReporterBase.submit_one(name, self, self.job_states, duration)
  File "/urlwatch/lib/urlwatch/reporters.py", line 113, in submit_one
    subclass(report, cfg, job_states, duration).submit()
  File "/urlwatch/lib/urlwatch/reporters.py", line 593, in submit
    for chat_id in chat_ids:
TypeError: 'int' object is not iterable

**Comment by schafsam** [comment]
Does your config file follow the syntax
    `chat_id: '88888888'`
Especially the chat id surrounded with quotations?

**Comment by ramelito** [comment]
Hi, thanks for pointing this out. My old config had a chat id without quotations, now i fixed it.
Issue can be closed.
