### ISSUE TITLE
module 'cgi' has no attribute 'escape'

### ISSUE THREAD

**Issue by noelkelly** [thp/urlwatch#616]
Issue using SMTP method on Ubuntu 20.04.1 with urlwatch 2.17 which is reported here but I can't find reference to it here: https://bugzilla.redhat.com/show_bug.cgi?id=1827745

```
2021-01-21 09:49:53,750 reporters INFO: Submitting with email (<class 'urlwatch.reporters.EMailReporter'>)
Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 111, in <module>
    urlwatch_command.run()
  File "/usr/lib/python3/dist-packages/urlwatch/command.py", line 295, in run
    self.urlwatcher.close()
  File "/usr/lib/python3/dist-packages/urlwatch/main.py", line 99, in close
    self.report.finish()
  File "/usr/lib/python3/dist-packages/urlwatch/handler.py", line 159, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/usr/lib/python3/dist-packages/urlwatch/reporters.py", line 103, in submit_all
    subclass(report, cfg, job_states, duration).submit()
  File "/usr/lib/python3/dist-packages/urlwatch/reporters.py", line 408, in submit
    body_html = '\n'.join(self.convert(HtmlReporter).submit())
  File "/usr/lib/python3/dist-packages/urlwatch/reporters.py", line 149, in submit
    yield from (str(part) for part in self._parts())
  File "/usr/lib/python3/dist-packages/urlwatch/reporters.py", line 149, in <genexpr>
    yield from (str(part) for part in self._parts())
  File "/usr/lib/python3/dist-packages/urlwatch/reporters.py", line 183, in _parts
    yield SafeHtml(title).format(verb=job_state.verb,
  File "/usr/lib/python3/dist-packages/urlwatch/reporters.py", line 144, in format
    **{k: cgi.escape(str(v)) for k, v in kwargs.items()})
  File "/usr/lib/python3/dist-packages/urlwatch/reporters.py", line 144, in <dictcomp>
    **{k: cgi.escape(str(v)) for k, v in kwargs.items()})
AttributeError: module 'cgi' has no attribute 'escape'

```

**Comment by kongomongo** [comment]
is the package somehow modified? check https://github.com/thp/urlwatch/blob/4eb9391829267f42e669988a91cff6cbe112d067/lib/urlwatch/reporters.py#L142, the source should be:

```
        return str(self).format(*(html.escape(str(arg)) for arg in args),
                                **{k: html.escape(str(v)) for k, v in kwargs.items()})
```

**Comment by kongomongo** [comment]
oh right, must be urlwatch 2.18 or older...
