### ISSUE TITLE
Freeze during 'navigate' jobs will prevent urlwatch from showing diffs

### ISSUE THREAD

**Issue by Markus00000** [thp/urlwatch#621]
`navigate` jobs can sometimes cause urlwatch to freeze with the exception below. As urlwatch will not terminate, it can only be killed. At this point, the retrieved data of some jobs might have already been written to the database.

As killing urlwatch will prevent displaying the diff output, only inspecting the SQLite database and doing manual diffs will reveal the data. While the data is not lost, it is cumbersome to retrieve.

Suggestions:

* If the retrieved data were only saved to the database *after* it was output, this way of missing diffs would be prevented.
* A timeout should allow urlwatch to still terminate when this exception occurs.
* Provide a convenient way to show past diffs that might have been missed due to exceptions or user error. (Might be worth a separate issue.)

The exception:

    $ urlwatch
    [E:pyppeteer.connection] connection unexpectedly closed
    Task exception was never retrieved
    future: <Task finished name='Task-864' coro=<Connection._async_send() done, defined at /usr/lib/python3.9/site-packages/pyppeteer/connection.py:69> exception=InvalidStateError('invalid state')>
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/websockets/protocol.py", line 827, in transfer_data
        message = await self.read_message()
      File "/usr/lib/python3.9/site-packages/websockets/protocol.py", line 895, in read_message
        frame = await self.read_data_frame(max_size=self.max_size)
      File "/usr/lib/python3.9/site-packages/websockets/protocol.py", line 971, in read_data_frame
        frame = await self.read_frame(max_size)
      File "/usr/lib/python3.9/site-packages/websockets/protocol.py", line 1047, in read_frame
        frame = await Frame.read(
      File "/usr/lib/python3.9/site-packages/websockets/framing.py", line 105, in read
        data = await reader(2)
      File "/usr/lib/python3.9/asyncio/streams.py", line 721, in readexactly
        raise exceptions.IncompleteReadError(incomplete, n)
    asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/pyppeteer/connection.py", line 73, in _async_send
        await self.connection.send(msg)
      File "/usr/lib/python3.9/site-packages/websockets/protocol.py", line 555, in send
        await self.ensure_open()
      File "/usr/lib/python3.9/site-packages/websockets/protocol.py", line 803, in ensure_open
        raise self.connection_closed_exc()
    websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/pyppeteer/connection.py", line 79, in _async_send
        await self.dispose()
      File "/usr/lib/python3.9/site-packages/pyppeteer/connection.py", line 170, in dispose
        await self._on_close()
      File "/usr/lib/python3.9/site-packages/pyppeteer/connection.py", line 151, in _on_close
        cb.set_exception(_rewriteError(
    asyncio.exceptions.InvalidStateError: invalid state

After pressing `ctrl+c` this output is added and urlwatch will still not terminate:

    ^CTraceback (most recent call last):
      File "/usr/bin/urlwatch", line 33, in <module>
        sys.exit(load_entry_point('urlwatch==2.22', 'console_scripts', 'urlwatch')())
      File "/usr/lib/python3.9/site-packages/urlwatch/cli.py", line 112, in main
        urlwatch_command.run()
      File "/usr/lib/python3.9/site-packages/urlwatch/command.py", line 409, in run
        self.urlwatcher.run_jobs()
      File "/usr/lib/python3.9/site-packages/urlwatch/main.py", line 94, in run_jobs
        run_jobs(self)
      File "/usr/lib/python3.9/site-packages/urlwatch/worker.py", line 61, in run_jobs
        for job_state in run_parallel(lambda job_state: job_state.process(),
      File "/usr/lib/python3.9/site-packages/urlwatch/worker.py", line 46, in run_parallel
        for future in concurrent.futures.as_completed(executor.submit(func, item) for item in items):
      File "/usr/lib/python3.9/concurrent/futures/_base.py", line 245, in as_completed
        waiter.event.wait(wait_timeout)
      File "/usr/lib/python3.9/threading.py", line 574, in wait
        signaled = self._cond.wait(timeout)
      File "/usr/lib/python3.9/threading.py", line 312, in wait
        waiter.acquire()
      File "/usr/lib/python3.9/site-packages/pyppeteer/launcher.py", line 152, in _close_process
        self._loop.run_until_complete(self.killChrome())
      File "/usr/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
        self._check_running()
      File "/usr/lib/python3.9/asyncio/base_events.py", line 578, in _check_running
        raise RuntimeError('This event loop is already running')
    RuntimeError: This event loop is already running

Re-running the same jobs will not show the missed diffs.

The jobs follow this format:

    name: "Test"
    navigate: "http://example.com/"
    filter:
      - css: .some-class
      - html2text
      - shellpipe: xargs some-script

I have not changed the configuration for `navigate` jobs:

    job_defaults:
      all: {}
      browser: {}

Packages:

* urlwatch 2.22
* python-pyppeteer 0.2.5

**Comment by Th30phaN3** [comment]
I'm having the same issue as described. 

I have the following configuration for default jobs:
`
job_defaults:
  url:
    max_tries: 2
    ignore_connection_errors: true
    ignore_timeout_errors: true
    diff_filter:
      - grep: '^[@+]'
  `

Packages:
www-misc/urlwatch 2.22 (installed via portage / gentoo tree)
dev-python/pyppeteer 0.2.5 (installed via portage / pentoo tree)

**Comment by mborsetti** [comment]
You might want to check out the fork optimized for HTML workloads called `webchanges` at https://pypi.org/project/webchanges/ as quite a lot of work has been made there to make Pyppeteer-based browsing (i.e. "navigate") stable. 

The latest version, 3.2.4, includes the following improvements for jobs using Pyppeteer:
  * Increased reliability from replacing the legacy custom code managing the asyncio event loop, finalizing asynchronous generators, and closing the threadpool with Python's bult-in ``asyncio.run()`` (only if running Python 3.7 or higher)
  * Higher stability from reduction in concurrency
  * More capability from using the same Chromium browsing engine powering the latest Chrome (version 89)
  * Much more flexibility and control from new directives:
     * ``chromium_revision``
     * ``switches``
     * ``wait_until``
     * ``ignore_https_errors``
     * ``wait_for_navigate``
     * ``wait_for``
     * ``user_data_dir``
     * ``block_elements``
     *  ``cookies``
     * ``headers``
     * ``http_proxy``
     * ``https_proxy``
     * ``timeout``

If you are running in a low-memory environment (or a container), you may want to follow [this tip](https://webchanges.readthedocs.io/en/stable/advanced.html#running-use-browser-true-jobs-in-low-memory-environments).

`webchanges` 3.2.4 has [plenty of other improvements](https://webchanges.readthedocs.io/en/stable/migration.html) throughout as well!

**Comment by mborsetti** [comment]
@Markus00000

> As killing urlwatch will prevent displaying the diff output, only inspecting the SQLite database and doing manual diffs will reveal the data. While the data is not lost, it is cumbersome to retrieve.

This issue has been addressed in ``webchanges`` 3.2.4 with the ability to roll back the database. If after rolling back the database you rerun the program, you will get the diffs automatically. See https://webchanges.readthedocs.io/en/stable/cli.html#roll-back-the-snapshot-database.  It may be a bit "crude", but it works.

> Suggestions:
> 
> * If the retrieved data were only saved to the database _after_ it was output, this way of missing diffs would be prevented.
> * A timeout should allow urlwatch to still terminate when this exception occurs.
> * Provide a convenient way to show past diffs that might have been missed due to exceptions or user error. (Might be worth a separate issue.)

These are great suggestions, thanks; food for thought and future improvements.

**Comment by mborsetti** [comment]
@Markus00000 Excellent, thanks for confirming this.

Definitely open an [issue](https://github.com/mborsetti/webchanges/issues) if you encounter a problem or have any suggestions!

**Comment by mborsetti** [comment]
@Markus00000 [`webchanges` 3.4.0](https://pypi.org/project/webchanges/), just released, now implements your excellent suggestion:
> If the retrieved data were only saved to the database after it was output, this way of missing diffs would be prevented.

It also still keeps the ability to manually [rollback the database](https://webchanges.readthedocs.io/en/stable/cli.html#roll-back-the-snapshot-database) and [redisplay historical diffs](https://webchanges.readthedocs.io/en/stable/cli.html#show-diff-from-saved-snapshots).

Furthermore, the database no longer grows to infinity in size, but by default only the last 4 snapshots ([configurable](https://webchanges.readthedocs.io/en/stable/cli.html#maximum-number-of-snapshots-to-save)) are saved.

**Comment by thp** [comment]
@mborsetti Please fix the licensing issue: https://github.com/mborsetti/webchanges/issues/30
