### ISSUE TITLE
navigate does not work

### ISSUE THREAD

**Issue by A6669** [thp/urlwatch#638]
when I run urlwatch,

> Exception while releasing resources for job: <browser navigate='https://pypi.org/project/urlwatch/' name='urlwatch' filter=[{'xpath': '/html/body/main/div[1]/div/div[1]/h1'}, {'html2text': {'method': 'pyhtml2text', 'unicode_snob': True, 'body_width': 0, 'inline_links': False, 'ignore_links': True, 'ignore_images': True, 'pad_tables': False, 'single_line_break': True}}, {'sort': None}, {'strip': None}] max_tries=2>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/urlwatch/handler.py", line 78, in __exit__
>     self.job.main_thread_exit()
>   File "/usr/local/lib/python3.9/site-packages/urlwatch/jobs.py", line 379, in main_thread_exit
>     self.ctx.close()
> AttributeError: 'BrowserJob' object has no attribute 'ctx'
if I use url='https://pypi.org/project/urlwatch/' , then there is no such issue.
so how to fix it if I want to use navigate?
I use python 3.9 and urlwatch2.23
OS:mac 11.2.3
thank you.

**Comment by mborsetti** [comment]
You way want to try the [_webchanges_ ](https://webchanges.readthedocs.io/en/stable/migration.html) fork, which is optimized for web browsing/HTML and has many improvements in the code running the web browsing engine (and is pre-release tested on Python 3.9 on MacOS).

**Comment by thp** [comment]
@mborsetti Also here, you keep advertising your fork as fork of urlwatch, but are not adhering to the license requirements: https://github.com/mborsetti/webchanges/issues/30
