### ISSUE TITLE
inaccurate jq documentation

### ISSUE THREAD

**Issue by fishstik** [thp/urlwatch#642]
The [jq section](https://github.com/thp/urlwatch/blob/8f15eb6/docs/source/filters.rst#filtering-json-response-data-using-jq-selectors) in the filters documentation gives an example usage of the jq filter:
```
url: https://example.net/jobs.json
filter:
   - jq:
      query: '.[].title'
```
However when I try this, I get the following error:
```
Traceback (most recent call last):
  File "/home/pi/dev/urlwatch/urlwatch/lib/urlwatch/handler.py", line 120, in process
    data = FilterBase.process(filter_kind, subfilter, self, data)
  File "/home/pi/dev/urlwatch/urlwatch/lib/urlwatch/filters.py", line 187, in process
    return filtercls(state.job, state).filter(data, subfilter)
  File "/home/pi/dev/urlwatch/urlwatch/lib/urlwatch/filters.py", line 902, in filter
    raise ValueError('{} filter needs a query'.format(self.__kind__))
ValueError: jq filter needs a query
```
It works with the following filter notation:
```
url: https://example.net/jobs.json
filter:
   - jq: '.[].title'
```

**Comment by thp** [comment]
Hm, weird -- the following works for me:
```
url: https://api.github.com/repos/voxpupuli/puppet-rundeck/tags
filter:
 - jq:
    query: '.[0].name'
```

Which version of urlwatch are you using?

**Comment by fishstik** [comment]
I'm now unable to reproduce this. Not sure what caused the error initially.
