### ISSUE TITLE
 Unknown filter kind: jq

### ISSUE THREAD

**Issue by jonathanfmorgan** [thp/urlwatch#649]
I'm sure I'm doing something wrong, but urlwatch can't seem to find jq. Can anyone help? Thanks!

Traceback (most recent call last):
  File "/usr/local/bin/urlwatch", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/cli.py", line 108, in main
    urlwatch = Urlwatch(command_config, config_storage, cache_storage, urls_storage)
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/main.py", line 66, in __init__
    self.load_jobs()
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/main.py", line 87, in load_jobs
    jobs = self.urls_storage.load_secure()
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/storage.py", line 303, in load_secure
    if shelljob_errors and any(is_shell_job(job) for job in jobs):
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/storage.py", line 303, in <genexpr>
    if shelljob_errors and any(is_shell_job(job) for job in jobs):
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/storage.py", line 291, in is_shell_job
    for filter_kind, subfilter in FilterBase.normalize_filter_list(job.filter):
  File "/usr/local/lib/python3.5/dist-packages/urlwatch/filters.py", line 95, in normalize_filter_list
    raise ValueError('Unknown filter kind: {} (subfilter {})'.format(filter_kind, subfilter))
ValueError: Unknown filter kind: jq (subfilter {'query': '.features|.[]|.attributes|"\\(.Provider_Type) - \\(.Provider_Name) - \\(.Address) - \\(.City) - \\(.Province) - \\(.Phone) - \\(.Status) - \\(.Vaccine_Comments)"'})

xxx:~$ sudo pip show jq
Name: jq
Version: 1.1.3
Summary: jq is a lightweight and flexible JSON processor.
Home-page: http://github.com/mwilliamson/jq.py
Author: Michael Williamson
Author-email: None
License: BSD 2-Clause
Location: /usr/local/lib/python3.5/dist-packages
Requires:
Required-by:

xxx:~$ sudo pip show urlwatch
Name: urlwatch
Version: 2.21
Summary: urlwatch monitors webpages for you
Home-page: https://thp.io/2008/urlwatch/
Author: Thomas Perl
Author-email: m@thp.io
License: BSD
Location: /usr/local/lib/python3.5/dist-packages
Requires: requests, cssselect, lxml, PyYAML, keyring, appdirs, minidb
Required-by:

**Comment by jonathanfmorgan** [comment]
I upgraded Python to 3.6, reinstalled urlwatch and jq, and it seems to be fine now.
