### ISSUE TITLE
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

### ISSUE THREAD

**Issue by jprokos** [thp/urlwatch#651]
Been running the same jobs for almost a year and today two went haywire for no apparent reason.

jobs and error messages below. 

The only thing I can think of that might be related is that GitHub sent me an email asking me to reset my authentication token. I updated my token a few days before this issue began. I am not exactly sure why or how when it comes to this token or if it's even related to urlwatch.

TIA for any help.

> We noticed your personal access token, Scopeless token, has an outdated format and was used to access the GitHub API on June 19th, 2021 at 20:34 (UTC) with a user-agent header of python-requests/2.25.1.

```
--- # SwimSwam
name: 23_SwimSwam News [USA Swimming, Time Standard, National Age Group]
url: "https://swimswam.com/feed/#1"
filter:
   - xpath:
      path: '//item/description/text()'
      exclude: a
      method: xml
   - grep: (?i)"usa\sswimming"|"time.*standard"|"national\sage\sgroup"
   - html2text: re
--- # SwimSwam
name: 24_SwimSwam News [NAG]
url: "https://swimswam.com/feed/#2"
filter:
   - xpath:
      path: '//item/description/text()'
      exclude: a
      method: xml
   - shellpipe: "grep 'NAG'; > /dev/null 2>&1"
   - html2text: re
--- # SwimSwam
```

```

urlwatch
==========
01. ERROR: 23_SwimSwam News [USA Swimming, Time Standard, National Age Group]
02. ERROR: 24_SwimSwam News [NAG]
==========

----------
ERROR: 23_SwimSwam News [USA Swimming, Time Standard, National Age Group] ( https://swimswam.com/feed/#1 )
----------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urlwatch/filters.py", line 696, in _get_filtered_elements
    root = etree.fromstring(self.data, self.parser)
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1891, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urlwatch/handler.py", line 120, in process
    data = FilterBase.process(filter_kind, subfilter, self, data)
  File "/usr/local/lib/python3.9/site-packages/urlwatch/filters.py", line 187, in process
    return filtercls(state.job, state).filter(data, subfilter)
  File "/usr/local/lib/python3.9/site-packages/urlwatch/filters.py", line 771, in filter
    return lxml_parser.get_filtered_data()
  File "/usr/local/lib/python3.9/site-packages/urlwatch/filters.py", line 721, in get_filtered_data
    elements = list(self._get_filtered_elements())
  File "/usr/local/lib/python3.9/site-packages/urlwatch/filters.py", line 703, in _get_filtered_elements
    root = etree.fromstring(self.data, self.parser)
  File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1777, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 105257
lxml.etree.XMLSyntaxError: internal error: Huge input lookup, line 105257, column 4
----------
```

**Comment by mborsetti** [comment]
I've tried the above jobs using the [_webchanges_ ](https://webchanges.readthedocs.io/en/stable/migration.html) fork, which is optimized for web browsing/HTML, and they work fine. Not sure what's the issue here, but that code has been modernized in the fork and optimized for handling of Unicode.

```
ubuntu:~$ webchanges --jobs jobs-test --test 1

23_SwimSwam News [USA Swimming, Time Standard, National Age Group]
------------------------------------------------------------------


ubuntu:~$ webchanges --jobs jobs-test --test 2
/home/ubuntu/.local/lib/python3.9/site-packages/webchanges/filters.py:1093: UserWarning: If possible replace the 'shellpipe' filter with the 'execute' one for security reasons
  warnings.warn("If possible replace the 'shellpipe' filter with the 'execute' one for security reasons")

24_SwimSwam News [NAG]
----------------------
```
