### ISSUE TITLE
Certificate verification error in openSUSE

### ISSUE THREAD

**Issue by nemysis** [thp/urlwatch#81]
I get when use urlwatch

```\n
urlwatch
Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 397, in <module>
    main(parser.parse_args())
  File "/usr/bin/urlwatch", line 364, in main
    report.finish()
  File "/usr/lib/python3.4/site-packages/urlwatch/handler.py", line 128, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/usr/lib/python3.4/site-packages/urlwatch/reporters.py", line 89, in submit_all
    cls(report, cfg, job_states, duration).submit()
  File "/usr/lib/python3.4/site-packages/urlwatch/reporters.py", line 304, in submit
    body = '\n'.join(super().submit())
  File "/usr/lib/python3.4/site-packages/urlwatch/reporters.py", line 220, in submit
    summary_part, details_part = self._format_output(job_state, line_length)
  File "/usr/lib/python3.4/site-packages/urlwatch/reporters.py", line 262, in _format_output
    pretty_summary = ': '.join((job_state.verb.upper(), pretty_name))
TypeError: sequence item 1: expected str instance, NoneType found
```

What is missed?

**Comment by thp** [comment]
Which reporters do you have enabled and for which pages?

**Comment by nemysis** [comment]
I use now older version for .urlwatch (backup)

and get

```\n
urlwatch
===========================================================================
01. CHANGED: http://ankisrs.net/download/mirror/
02. ERROR: https://www.gropp.org/?id=projects&sub=bwm-ng
03. ERROR: https://sourceforge.net/p/blobandconquer/code/ci/master/tree/
04. ERROR: https://sourceforge.net/projects/atomiks/files/
05. ERROR: http://opensnc.sourceforge.net/alfont/
06. ERROR: https://www.7kfans.com/wiki/index.php/Download
07. ERROR: https://sourceforge.net/projects/blobwars/files/
08. CHANGED: http://www.chickensforlinux.com/download.php
===========================================================================

---------------------------------------------------------------------------
CHANGED: http://ankisrs.net/download/mirror/
---------------------------------------------------------------------------
--- @   Wed, 24 Feb 2016 20:53:36 +0100
+++ @   Wed, 13 Jul 2016 00:17:36 +0200
@@ -2,26 +2,27 @@
 <head><title>Index of /download/mirror/</title></head>
 <body bgcolor="white">
 <h1>Index of /download/mirror/</h1><hr><pre><a href="../">../</a>
-<a href="archive/">archive/</a>                                           10-Feb-2015 17:29       -                                                 [67/9656]
-<a href="beta/">beta/</a>                                              29-Sep-2015 14:36       -
-<a href="videos/">videos/</a>                                            25-Feb-2014 22:07       -
-<a href="anki-2.0.31.deb">anki-2.0.31.deb</a>                                    19-Oct-2014 19:05      3M
-<a href="anki-2.0.31.dmg">anki-2.0.31.dmg</a>                                    19-Oct-2014 19:05     28M
-<a href="anki-2.0.31.exe">anki-2.0.31.exe</a>                                    19-Oct-2014 19:05     22M
-<a href="anki-2.0.31.qt47.dmg">anki-2.0.31.qt47.dmg</a>                               19-Oct-2014 19:05     29M
-<a href="anki-2.0.31.qt47.exe">anki-2.0.31.qt47.exe</a>                               19-Oct-2014 19:05     22M
-<a href="anki-2.0.31.tgz">anki-2.0.31.tgz</a>                                    19-Oct-2014 19:05      3M
-<a href="anki-2.0.32.deb">anki-2.0.32.deb</a>                                    25-Mar-2015 01:25      3M
-<a href="anki-2.0.32.dmg">anki-2.0.32.dmg</a>                                    25-Mar-2015 01:25     28M
-<a href="anki-2.0.32.exe">anki-2.0.32.exe</a>                                    25-Mar-2015 01:25     22M
-<a href="anki-2.0.32.qt47.dmg">anki-2.0.32.qt47.dmg</a>                               25-Mar-2015 01:25     29M
-<a href="anki-2.0.32.qt47.exe">anki-2.0.32.qt47.exe</a>                               25-Mar-2015 01:25     22M
-<a href="anki-2.0.32.tgz">anki-2.0.32.tgz</a>                                    25-Mar-2015 01:25      3M
-<a href="anki-2.0.33.deb">anki-2.0.33.deb</a>                                    11-Oct-2015 20:35      3M
-<a href="anki-2.0.33.dmg">anki-2.0.33.dmg</a>                                    11-Oct-2015 20:35     28M
-<a href="anki-2.0.33.exe">anki-2.0.33.exe</a>                                    11-Oct-2015 20:35     22M
-<a href="anki-2.0.33.qt47.dmg">anki-2.0.33.qt47.dmg</a>                               11-Oct-2015 20:35     29M
-<a href="anki-2.0.33.qt47.exe">anki-2.0.33.qt47.exe</a>                               11-Oct-2015 20:35     22M
-<a href="anki-2.0.33.tgz">anki-2.0.33.tgz</a>                                    11-Oct-2015 20:35      3M
+<a href="alpha/">alpha/</a>                                             11-Jul-2016 14:47       -
+<a href="archive/">archive/</a>                                           10-Feb-2015 16:29       -
+<a href="beta/">beta/</a>                                              09-Apr-2016 10:49       -
+<a href="videos/">videos/</a>                                            25-Feb-2014 21:07       -
+<a href="anki-2.0.34.deb">anki-2.0.34.deb</a>                                    27-Mar-2016 20:57      3M
+<a href="anki-2.0.34.dmg">anki-2.0.34.dmg</a>                                    27-Mar-2016 20:57     28M
+<a href="anki-2.0.34.exe">anki-2.0.34.exe</a>                                    27-Mar-2016 20:57     22M
+<a href="anki-2.0.34.qt47.dmg">anki-2.0.34.qt47.dmg</a>                               27-Mar-2016 20:57     29M
+<a href="anki-2.0.34.qt47.exe">anki-2.0.34.qt47.exe</a>                               27-Mar-2016 20:57     22M
+<a href="anki-2.0.34.tgz">anki-2.0.34.tgz</a>                                    27-Mar-2016 20:57      3M
+<a href="anki-2.0.35.deb">anki-2.0.35.deb</a>                                    05-Apr-2016 11:10      3M
+<a href="anki-2.0.35.dmg">anki-2.0.35.dmg</a>                                    05-Apr-2016 11:10     28M
+<a href="anki-2.0.35.exe">anki-2.0.35.exe</a>                                    05-Apr-2016 11:10     22M
+<a href="anki-2.0.35.qt47.dmg">anki-2.0.35.qt47.dmg</a>                               05-Apr-2016 11:10     29M
+<a href="anki-2.0.35.qt47.exe">anki-2.0.35.qt47.exe</a>                               05-Apr-2016 11:10     22M
+<a href="anki-2.0.35.tgz">anki-2.0.35.tgz</a>                                    05-Apr-2016 11:10      3M
+<a href="anki-2.0.36.deb">anki-2.0.36.deb</a>                                    10-Apr-2016 13:32      3M
+<a href="anki-2.0.36.dmg">anki-2.0.36.dmg</a>                                    10-Apr-2016 13:32     28M
+<a href="anki-2.0.36.exe">anki-2.0.36.exe</a>                                    10-Apr-2016 13:32     22M
+<a href="anki-2.0.36.qt47.dmg">anki-2.0.36.qt47.dmg</a>                               10-Apr-2016 13:32     29M
+<a href="anki-2.0.36.qt47.exe">anki-2.0.36.qt47.exe</a>                               10-Apr-2016 13:32     22M
+<a href="anki-2.0.36.tgz">anki-2.0.36.tgz</a>                                    10-Apr-2016 13:32      3M
 </pre><hr></body>
 </html>

---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://www.gropp.org/?id=projects&sub=bwm-ng
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://sourceforge.net/p/blobandconquer/code/ci/master/tree/
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://sourceforge.net/projects/atomiks/files/
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: http://opensnc.sourceforge.net/alfont/
---------------------------------------------------------------------------
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://www.7kfans.com/wiki/index.php/Download
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://sourceforge.net/projects/blobwars/files/
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------
---------------------------------------------------------------------------


---------------------------------------------------------------------------
CHANGED: http://www.chickensforlinux.com/download.php
---------------------------------------------------------------------------
--- @   Wed, 24 Feb 2016 20:53:37 +0100
+++ @   Wed, 13 Jul 2016 00:17:36 +0200
@@ -73,7 +73,7 @@
 <font color="#ffffff">
 
 <hr>
-4,903 people have downloaded this release</font>
+5,120 people have downloaded this release</font>
 
 </body>
 

---------------------------------------------------------------------------


-- 
urlwatch 2.5, Copyright 2008-2016 Thomas Perl
Website: http://thp.io/2008/urlwatch/
watched 15 URLs in 0 seconds
```

**Comment by thp** [comment]
Looks like your certificate store is messed up? (SSL errors)

**Comment by nemysis** [comment]
I have tried in not working .urlwatch

```
kind: name
```

have removed then and now get

```\n

dusko@nemysis3now:~/ > urlwatch
===========================================================================
01. ERROR: https://www.gropp.org/?id=projects&sub=bwm-ng
02. ERROR: http://opensnc.sourceforge.net/alfont/
03. ERROR: https://www.7kfans.com/wiki/index.php/Download
04. ERROR: https://sourceforge.net/projects/atomiks/files/
05. ERROR: https://sourceforge.net/p/blobandconquer/code/ci/master/tree/
06. ERROR: https://sourceforge.net/projects/blobwars/files/
07. ERROR: https://sourceforge.net/projects/chromium-bsu/files/Chromium%20B.S.U.%20source%20code/
08. ERROR: http://domination.sourceforge.net/
09. ERROR: http://domination.sourceforge.net/getmaps.shtml
10. ERROR: https://github.com/Mekire/double-cross
11. ERROR: http://eaglemode.sourceforge.net/download.html
12. ERROR: https://sourceforge.net/projects/extremetuxracer/files/releases/
13. ERROR: https://hexchat.github.io/downloads.html
14. ERROR: https://tracker.debian.org/pkg/hostname
15. ERROR: https://sourceforge.net/projects/foobillard/files/FooBillard-Sources/
16. ERROR: https://www.kde.org/announcements/
17. CHANGED: http://www.i-scream.org/libstatgrab/
18. ERROR: http://tomatoes.sourceforge.net/downloads.html
19. ERROR: https://pypi.python.org/pypi/managesieve
20. ERROR: http://lgames.sourceforge.net/index.php?project=LPairs
21. ERROR: http://lgames.sourceforge.net/index.php?project=LMarbles
22. ERROR: https://sourceforge.net/projects/mmario/files/Mega%20Mario%20Full%20Game/
23. ERROR: https://bitbucket.org/osslugaru/lugaru/downloads
24. ERROR: https://sourceforge.net/p/opensnc/code/HEAD/tree/opensurge/trunk/
25. ERROR: https://sourceforge.net/projects/pacmanarena/
26. ERROR: https://nmap.org/download.html
27. ERROR: http://kuthulu.com/iwscanner/index.php?module=download
28. ERROR: https://www.libsdl.org/projects/pipenightdreams/download.html
29. CHANGED: http://www.losersjuegos.com.ar/juegos/pongix
===========================================================================

---------------------------------------------------------------------------
ERROR: https://www.gropp.org/?id=projects&sub=bwm-ng
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: http://opensnc.sourceforge.net/alfont/
---------------------------------------------------------------------------
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://www.7kfans.com/wiki/index.php/Download
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://sourceforge.net/projects/atomiks/files/
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://sourceforge.net/p/blobandconquer/code/ci/master/tree/
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://sourceforge.net/projects/blobwars/files/
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://sourceforge.net/projects/chromium-bsu/files/Chromium%20B.S.U.%20source%20code/
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------
                                                                                                                                                    [106/9570]

---------------------------------------------------------------------------
ERROR: https://tracker.debian.org/pkg/hostname
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://sourceforge.net/projects/foobillard/files/FooBillard-Sources/
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://www.kde.org/announcements/
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
CHANGED: http://www.i-scream.org/libstatgrab/
---------------------------------------------------------------------------
--- @   Wed, 13 Jul 2016 00:33:37 +0200
+++ @   Wed, 13 Jul 2016 00:39:22 +0200
@@ -563,7 +563,7 @@
       </div>
       <div id="menu">
         <h3 class="heading">
-          <img src="//www.i-scream.org/logos/centrepoint.jpg" class="cornerlogo" alt="a random image"/>
+          <img src="//www.i-scream.org/logos/berlin-sunset.jpg" class="cornerlogo" alt="a random image"/>
           <br />
           Main
         </h3>

---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: http://tomatoes.sourceforge.net/downloads.html
---------------------------------------------------------------------------
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://pypi.python.org/pypi/managesieve
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: http://lgames.sourceforge.net/index.php?project=LPairs
---------------------------------------------------------------------------
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: http://lgames.sourceforge.net/index.php?project=LMarbles
---------------------------------------------------------------------------
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://sourceforge.net/projects/mmario/files/Mega%20Mario%20Full%20Game/
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://bitbucket.org/osslugaru/lugaru/downloads
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://sourceforge.net/p/opensnc/code/HEAD/tree/opensurge/trunk/
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://sourceforge.net/projects/pacmanarena/
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://nmap.org/download.html
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: http://kuthulu.com/iwscanner/index.php?module=download
---------------------------------------------------------------------------
404 Client Error: Not Found
---------------------------------------------------------------------------


---------------------------------------------------------------------------
ERROR: https://www.libsdl.org/projects/pipenightdreams/download.html
---------------------------------------------------------------------------
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
---------------------------------------------------------------------------


---------------------------------------------------------------------------
CHANGED: http://www.losersjuegos.com.ar/juegos/pongix
---------------------------------------------------------------------------
---------------------------------------------------------------------------
--- @   Wed, 13 Jul 2016 00:33:38 +0200
+++ @   Wed, 13 Jul 2016 00:39:22 +0200
@@ -57,7 +57,7 @@
 
         <div class='caja'>
             <h5>Usuario</h5>
-                                    <form class="button btn_login" method="get" action="/juegos/pongix"><div class="no"><input type="hidden" name="do" value="login" /><input type="hidden" name="sectok" value="55cd94c4aa83afb3cfc2344a5efd592c" /><input type="submit" value="Entrar" class="button" title="Entrar" /></div></form>        </div>
+                                    <form class="button btn_login" method="get" action="/juegos/pongix"><div class="no"><input type="hidden" name="do" value="login" /><input type="hidden" name="sectok" value="5f9cdcc33896c08c3207b794e1ea9f13" /><input type="submit" value="Entrar" class="button" title="Entrar" /></div></form>        </div>
 
         <div class='caja'>
             <h5>Buscar páginas</h5>
@@ -353,6 +353,6 @@
 
 </div>
 
-<div class="no"><img src="/lib/exe/indexer.php?id=juegos%3Apongix&amp;1468364622" width="1" height="1" alt=""  /></div>
+<div class="no"><img src="/lib/exe/indexer.php?id=juegos%3Apongix&amp;1468364966" width="1" height="1" alt=""  /></div>
 </body>
 </html>

---------------------------------------------------------------------------


-- 
urlwatch 2.5, Copyright 2008-2016 Thomas Perl
Website: http://thp.io/2008/urlwatch/
watched 49 URLs in 1 seconds
```

Ok how to fix SSL errors i use openSSL?

Have reinstalled

```\n
zypper in -f libopenssl-devel libopenssl1_0_0-32bit openssl perl-Crypt-OpenSSL-RSA perl-Crypt-OpenSSL-Random python-pyOpenSSL
```

**Comment by nemysis** [comment]
I have found openSUSE use

```
/var/lib/ca-certificates
```

Please add this to urlwatch

**Comment by thp** [comment]
There's no need to add this to urlwatch. Your system / distribution should set up `requests` correctly to find the certificates wherever they are, it's not urlwatch's responsibility to fix that for every distro.

See here: http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification
See also: http://docs.python-requests.org/en/master/user/advanced/#ca-certificates

Closing this as invalid, as this looks like a local misconfiguration or openSUSE-specific issue.

**Comment by vmassuchetto** [comment]
It is not acceptable to include an option to bypass the verification?

    Requests can also ignore verifying the SSL certificate if you set verify to False:
    >>> requests.get('https://kennethreitz.org', verify=False)

Would be easier than keep adding certificates to our systems.
