### ISSUE TITLE
How to use sendmail

### ISSUE THREAD

**Issue by marbon87** [thp/urlwatch#82]
Hi there,

since i cannot use smtp mailer anymore, because keyring forces me to use an encrypted keystore, i tried to use the sendmail-feature.
I configured the sendmail path and i can send mail from the console with 
``` echo test| sendmail -t example@google.com ```

But when i try to use urlwatch, i get an connection refused-error. How do i configure urlwatch with sendmail correctly?

**Comment by thp** [comment]
Can you post your config and the exact error message?

**Comment by marbon87** [comment]
my config is:

```
display:
  error: true
  new: true
  unchanged: false
report:
  email:
    enabled: true
    from: 'me@example.com'
    html: true
    sendmail:
        path: '/usr/bin/sendmail'
    subject: '{count} changes: {jobs}'
    to: 'me@example.com'
  html:
    diff: unified
  stdout:
    color: true
    enabled: true
  text:
    details: false
    footer: true
    line_length: 75
```

the error message is:
```
Traceback (most recent call last):
  File "/usr/bin/urlwatch", line 397, in <module>
    main(parser.parse_args())
  File "/usr/bin/urlwatch", line 364, in main
    report.finish()
  File "/usr/lib/python3.5/site-packages/urlwatch/handler.py", line 128, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/usr/lib/python3.5/site-packages/urlwatch/reporters.py", line 89, in submit_all
    cls(report, cfg, job_states, duration).submit()
  File "/usr/lib/python3.5/site-packages/urlwatch/reporters.py", line 360, in submit
    mailer.send(msg)
  File "/usr/lib/python3.5/site-packages/urlwatch/mailer.py", line 79, in send
    s = smtplib.SMTP(self.smtp_server, self.smtp_port)
  File "/usr/lib/python3.5/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.5/smtplib.py", line 335, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.5/smtplib.py", line 306, in _get_socket
    self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by sbraz** [comment]
Change the method here: https://github.com/thp/urlwatch/blob/master/lib/urlwatch/storage.py#L75
Excerpt from the code:
```py
        if self.config['method'] == "smtp":
            mailer = SMTPMailer(self.config['smtp']['host'], self.config['smtp']['port'],
                                self.config['smtp']['starttls'], self.config['smtp']['keyring'])
        elif self.config['method'] == "sendmail":
            mailer = SendmailMailer(self.config['sendmail']['path'])
        else:
            logger.error('Invalid entry for method {method}'.format(method = self.config['method']))
```

**Comment by marbon87** [comment]
@sbraz thx, that worked!
