### ISSUE TITLE
Sporadic SQLite error: Error binding parameter 0 - probably unsupported type.

### ISSUE THREAD

**Issue by jwm** [thp/urlwatch#96]
Hi Thomas, thanks for writing urlwatch, it's exactly what I needed.

I have it watching ~100 URLs and sporadically get an SQLite exception on a subset of URLs for that run. It doesn't happen with any URL(s) in particular, but it does happen regularly (perhaps not every single run, but most of the time) and usually happens for a few URLs in a run.

This is with urlwatch 2.5, minidb 2.0.1, SQLite 3.8.7.1, and Python 3.4.2 (the latter two are from Debian jessie packaging).

I put some debugging output in the affected exception handler. The query and args are:

```
  SELECT data, timestamp FROM CacheEntry WHERE guid = ? ORDER BY timestamp DESC LIMIT ?
  ['2483ad9118822dd4099841a766fc86b65625d20e', 1]
```

It's puzzling since I'd think the GUID would always be a string.

```
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/urlwatch/handler.py", line 65, in process
      self.load()
    File "/usr/lib/python3/dist-packages/urlwatch/handler.py", line 57, in load
      self.old_data, self.timestamp = self.cache_storage.load(self.job, self.job.get_guid())
    File "/usr/lib/python3/dist-packages/urlwatch/storage.py", line 322, in load
      where=CacheEntry.c.guid == guid, limit=1):
    File "/usr/local/lib/python3.4/dist-packages/minidb.py", line 932, in query
      return db.query(cls, select=select, where=where, order_by=order_by, group_by=group_by,
  limit=limit)
    File "/usr/local/lib/python3.4/dist-packages/minidb.py", line 401, in query
      result = self._execute(sql, args)
    File "/usr/local/lib/python3.4/dist-packages/minidb.py", line 158, in _execute
      return self.db.execute(sql, args)
  sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
```

**Comment by thp** [comment]
Do we have a test case that can reliably reproduce this is or is simply sporadic? Googling for that specific error message didn't yield anything that looks related.

**Comment by jwm** [comment]
Unfortunately, it's sporadic. It doesn't happen on every run, or even with certain URL(s). 😞

**Comment by thp** [comment]
Ok, leaving this open for now. Maybe somebody runs into it and then we can investigate.

**Comment by nblock** [comment]
This error occurs pretty often with this URL (but not always): ```https://h10145.www1.hpe.com/downloads/SoftwareReleases.aspx?ProductNumber=J9137A&lang=&cc=&prodSeriesId=```

**Comment by jwm** [comment]
FWIW, this happens even with only one worker (`MAX_WORKERS = 1`).

**Comment by copernico** [comment]
It happened to me with 2.6 today with url: https://www.bouncycastle.org/latest_releases.html

```
Traceback (most recent call last):
  File "/opt/urlwatch-2.6/lib/urlwatch/handler.py", line 62, in process
    self.load()
  File "/opt/urlwatch-2.6/lib/urlwatch/handler.py", line 54, in load
    self.old_data, self.timestamp = self.cache_storage.load(self.job, self.job.get_guid())
  File "/opt/urlwatch-2.6/lib/urlwatch/storage.py", line 474, in load
    where=CacheEntry.c.guid == guid, limit=1):
  File "/home/i064196/.local/lib/python3.5/site-packages/minidb.py", line 928, in query
    return db.query(cls, select=select, where=where, order_by=order_by, group_by=group_by, limit=limit)
  File "/home/i064196/.local/lib/python3.5/site-packages/minidb.py", line 395, in query
    result = self._execute(sql, args)
  File "/home/i064196/.local/lib/python3.5/site-packages/minidb.py", line 157, in _execute
    return self.db.execute(sql, args)
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
________________________________________
error: https://www.bouncycastle.org/latest_releases.html
Traceback (most recent call last):
  File "/opt/urlwatch-2.6/lib/urlwatch/handler.py", line 62, in process
    self.load()
  File "/opt/urlwatch-2.6/lib/urlwatch/handler.py", line 54, in load
    self.old_data, self.timestamp = self.cache_storage.load(self.job, self.job.get_guid())
  File "/opt/urlwatch-2.6/lib/urlwatch/storage.py", line 474, in load
    where=CacheEntry.c.guid == guid, limit=1):
  File "/home/i064196/.local/lib/python3.5/site-packages/minidb.py", line 928, in query
    return db.query(cls, select=select, where=where, order_by=order_by, group_by=group_by, limit=limit)
  File "/home/i064196/.local/lib/python3.5/site-packages/minidb.py", line 395, in query
    result = self._execute(sql, args)
  File "/home/i064196/.local/lib/python3.5/site-packages/minidb.py", line 157, in _execute
    return self.db.execute(sql, args)
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
________________________________________

```

**Comment by copernico** [comment]
And again today:

```
error: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8
Traceback (most recent call last):
  File "/opt/urlwatch-2.6/lib/urlwatch/handler.py", line 62, in process
    self.load()
  File "/opt/urlwatch-2.6/lib/urlwatch/handler.py", line 54, in load
    self.old_data, self.timestamp = self.cache_storage.load(self.job, self.job.get_guid())
  File "/opt/urlwatch-2.6/lib/urlwatch/storage.py", line 474, in load
    where=CacheEntry.c.guid == guid, limit=1):
  File "/home/i064196/.local/lib/python3.5/site-packages/minidb.py", line 928, in query
    return db.query(cls, select=select, where=where, order_by=order_by, group_by=group_by, limit=limit)
  File "/home/i064196/.local/lib/python3.5/site-packages/minidb.py", line 395, in query
    result = self._execute(sql, args)
  File "/home/i064196/.local/lib/python3.5/site-packages/minidb.py", line 157, in _execute
    return self.db.execute(sql, args)
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.

```

**Comment by copernico** [comment]
Don't know if that is just by chance or that page has some feature that triggers the error with higher likelihood, but the very same url failed today https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8

**Comment by nxbx** [comment]
Same issue, and it's sporadic. From time to time on different urls.

**Comment by nxbx** [comment]
Same issue, and it's sporadic. From time to time on different urls:
VPS | Ubuntu 14.04.5 LTS | 1GB RAM | Python 3.4.3

I solved the problem by trying on my old laptop with same urls list:
Linux Mint 19 (Tara) | 6 GB RAM | Python 3.6.7

Urlwatch version in both cases: 2.16

Try to change Python version, or increase RAM.

**Comment by jwm** [comment]
As a data point, this hasn't happened to me for some time, but I've long since upgraded to Debian Stretch (9.x) which includes Python 3.5.3 and SQLite 3.16.2. I'm running urlwatch 2.14 and minidb 2.0.2.
